### ISSUE TITLE
Wrong duration and strange splitting

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1686] opened 2016-05-06 02:00 UTC
Hello,

I think I found another bug, this time in the way the duration of tracks and the whole file are calculated when the initial segment info on duration is not correct. The following is mkvinfos output for segment-info and the last cluster of 6.mkv (which I uploaded to your ftp-server):
```
Muxeranwendung: Haali Matroska Writer b0 an 50
| + schreibende Anwendung: x264 r2665 a01e339 an 77
| + Zeitstempelskalierungsfaktor: 50000 an 98
| + Dauer: 114.880s (00:01:54.880) an 104
[...]
Cluster an 16509213
| + Cluster-Zeitstempel: 114.600s an 16509220
| + SimpleBlock (Spur Nummer 1, 1 Bild(er), Zeitstempel 114.600s = 00:01:54.600) an 16509225
|  + Bild mit Größe 10549
| + SimpleBlock (Spur Nummer 1, 1 Bild(er), Zeitstempel 114.520s = 00:01:54.520) an 16519781
|  + Bild mit Größe 3934
| + SimpleBlock (verwerfbar, Spur Nummer 1, 1 Bild(er), Zeitstempel 114.480s = 00:01:54.480) an 16523722
|  + Bild mit Größe 2643
| + SimpleBlock (verwerfbar, Spur Nummer 1, 1 Bild(er), Zeitstempel 114.560s = 00:01:54.560) an 16526372
|  + Bild mit Größe 3585
| + SimpleBlock (Spur Nummer 1, 1 Bild(er), Zeitstempel 114.720s = 00:01:54.720) an 16529964
|  + Bild mit Größe 14418
| + SimpleBlock (Spur Nummer 1, 1 Bild(er), Zeitstempel 114.680s = 00:01:54.680) an 16544389
|  + Bild mit Größe 2892
| + SimpleBlock (verwerfbar, Spur Nummer 1, 1 Bild(er), Zeitstempel 114.640s = 00:01:54.640) an 16547288
|  + Bild mit Größe 3464
| + SimpleBlock (Spur Nummer 1, 1 Bild(er), Zeitstempel 114.880s = 00:01:54.880) an 16550759
|  + Bild mit Größe 10965
| + SimpleBlock (Spur Nummer 1, 1 Bild(er), Zeitstempel 114.800s = 00:01:54.800) an 16561731
|  + Bild mit Größe 7254
| + SimpleBlock (verwerfbar, Spur Nummer 1, 1 Bild(er), Zeitstempel 114.760s = 00:01:54.760) an 16568992
|  + Bild mit Größe 2763
| + SimpleBlock (verwerfbar, Spur Nummer 1, 1 Bild(er), Zeitstempel 114.840s = 00:01:54.840) an 16571762
|  + Bild mit Größe 2792
```
This file has been created using x264.exe with an inbuilt haali mkv writer. It's length is 1:54.920, not 1:54.880. Haali seems to ignore the fact that the last frame in storage order is not the last frame in display order (or they ignore the duration of the last frame as a matter of principle; by the way, the cluster timestamp is bigger than a timestamp of a frame in the cluster which might be against the spec). This seems to be a bug in Haali, but if I merge this mkv with mkvmerge (to 6 (1).mkv), mkvmerge uses the same wrong length (both in the header and in the tags) and that's a bug in mkvmerge. If I extract the h264 and remux it with a fps of 25 (to 6 (2).mkv), I get the correct duration. So here is another instance in which the modules for framed and unframed h264 give different results.
And there is a strange consequence of these different duration elements: If I split all these three files after the timecode 00:01:00, the starting file derived from 6 (2).mkv shows the correct length of 63.200s, whereas the two starting files generated from 6.mkv and 6 (1).mkv show a length of 63.160s, although the last timecode of the last frame is 63.160s and its duration is 40ms. Notice that the last frame in storage order is the last frame in display order (the one with the highest timecode) so that this issue seems to emanate from the erroneous initial duration and not from a bug in mkvtoolnix' handling of situations like the one above where the last frame in the file is not the one with the highest timestamp (this was my initial guess; it also might be related to [1170](https://github.com/mbunkus/mkvtoolnix/issues/1170)). The second parts belonging to 6.mkv and 6 (1).mkv are even weirder: The beginning of the first cluster and the first frame are both at 0.040s. The highest timecode of a frame is 51.720s, so that the duration is 51.720s, but both the header and the tags say that these files have a duration of 51.680s. (The sum of the reported lengths of the two parts is 40ms less than the reported lengths of 6.mkv or 6 (1).mkv and 80ms less than the real length.) The second part derived from 6 (2).mkv is a normal file.
Honestly speaking, I am quite suprised that you use the content of the segment-information "duration"-field at all. What's the advantage in doing so? I can understand that the wrong length of the first parts leads to the second files starting at 0.040s (you probably just subtract the length of the first file from the timecodes of the frames in the second half to get the timecodes for the second file), but I don't understand how the length of the input file enters the equation. (And I do not even want to investigate what happens with multiple input files -- my guess is that a wrong length of the first video track matters when it comes to this bug.)
Oh, and please tell me if you can reproduce this.

Andi

**Comment by mbunkus** [comment] 2016-05-06 11:11
Even if it may seem so mkvmerge does NOT use the duration information from the source file, neither the one stored in the segment info nor the durations stored in the track tags.

As you know mkvmerge has two output modules for h.264 video. One is used when the source is an unframed bitstream (e.g. raw h.264 files, MPEG transport streams). This one has to determine where the frame boundaries are, parses all the NALUs it finds. It is rather slow due to these operations.

The other output module is used when the source is already framed (e.g. reading from Matroska or MP4). This module relies on the source having done most of the expensive work already; it therefore doesn't do deep NALU parsing. It's quite a bit faster than the other output module.

However, the second (framed) output module's drawback is that it's relying on the source container providing all the required information. This includes the frame duration.

The sample file you've uploaded does not provide the frame duration at the container level. There's neither a BlockDuration element present for the last frame(s), nor is there a "default duration" element for the track itself. Therefore the output module does not know the frame's duration and can only use its timestamp for the calculation of the track's total length. This is by design – otherwise it would require deep parsing of all NALUs and giving up on the speed advantage.

Therefore the second output module's behavior won't be changed.

The observed peculiarities regarding splitting can be attributed to the very same underlying issues.

However, it's likely that I'll re-write the whole h.264 handling and remove the faster but less precise output module (favoring correctness over speed) in order to fix #1673. If that happens then the current bug will be solved automatically by that re-write as well as the deeper inspection allows the output module to fall back on the timing data from the bitstream if the source container doesnt' provide durations of its own.

Fixing #1673 requires that #1671 be fixed first, though. And neither of those two bugs is entirely trivial to fix; quite the opposite.

Summary: either there will be a re-write for #1673 which will fix this bug, too, or there won't be a re-write and then I won't fix this bug either. Therefore I'm closing the issue again.

**Closed by mbunkus** 2016-05-06 11:11 UTC

**Comment by mkver** [comment] 2016-05-06 12:28
Thanks for the comprehensive answer. I entirely missed that there is no default duration in this track. But if I understand [this post from you](https://github.com/mbunkus/mkvtoolnix/issues/1170#issuecomment-95059393) correctly, then you actually should not go back to the bitstream timings for the split, but use the difference to the next frame in presentation order as the frame's duration. The container actually contains the durations for all but the very last frame, but mkvmerge doesn't handle the third routine from the cited post. This actually means that this isn't really a h264-issue per se. Or am I totally mistaken now?

**Comment by mbunkus** [comment] 2016-05-06 12:29
No, but that won't be fixed any time soon either.
