### ISSUE TITLE
MKVToolnix is not setting default track flags at all

### ISSUE THREAD

**Issue by smitbret** [mbunkus/mkvtoolnix#1716] opened 2016-06-06 15:57 UTC
I am remuxing some video files and I want to set the "Default Track Flag" for the subtitles to "No".  In the past this has worked fine but it seems like it doesn't work since v9.  Despite setting the "Default Track Flag" to "No", the flag remains "Determine Automatically" after the remux.  This results in the subtitle being displayed automatically on my playback devices.  I have tried to modify the Flags with the Header Editor and/o completely remuxing but it doesn't make any difference.

I am currently on v9.2.0.

**Comment by mbunkus** [comment] 2016-06-06 16:09
This is a misunderstanding. The GUI does NOT set the drop-down box to the value the flag currently has in the source file. This is intentional.

You should rather pay attention to the track list column labeled "default track in output" which contains the interpreted view of what the flag will be in the output file for any given set of settings.

If you want to know what the flag is currently set to in a file then the "merge" tool is not the right tool for the job. Instead use the header editor of mkvinfo's GUI.

**Comment by mbunkus** [comment] 2016-06-06 16:10
Note that I have also just verified that this is working as intended. The flag is set to "no" in the output file.

**Closed by mbunkus** 2016-06-06 16:09 UTC
