### ISSUE TITLE
Remuxing .ts 1080i AVC Interlaced into .mkv results in lost frames in the beginning of the video in DGIndexNV

### ISSUE THREAD

**Issue by dejong12** [mbunkus/mkvtoolnix#1409] opened 2015-08-19 21:25 UTC
I have a 1080i AVC .ts recording and when I cut it and remux the video into .mkv with mkvmerge GUI 8.3.0, the first ~14 frames are lost when processing the .mkv with DGIndexNV. I've spoken with the creator of DGIndexNV and he said something hoses up in mmg.exe when remuxing a .ts directly. When remuxing the elementary streams into .mkv, the lost frames are kept, so there's something going wrong when importing the .ts file into mkvmerge GUI. I've uploaded a sample .ts recording in your ftp, named test.ts.

**Comment by mbunkus** [comment] 2015-08-20 17:17
Thanks for the report, but I cannot really reproduce the issue. I've done the following tests:

1. Merged directly from test.ts to Matroska with mkvmerge (only the video track).
2. Extracted the video track from test.ts to an elementary .h264 file with ffmpeg (`ffmpeg -i test.ts -an -vcodec copy ffmpeg.h264`), then merged that elementary file to Matroska with mkvmerge.
3. Extracted the video track from test.ts to an elementary .h264 with tsMuxer (with the help of tsMuxerGUI), then merged that elementary file to Matroska with mkvmerge.

Finally I ran mkvinfo on all three resulting Matroska files, and in each case the file contained 6002 frames.

**Comment by mbunkus** [comment] 2015-08-20 17:46
Please note the following: your `test.ts` does not start with SPS/PPS NALUs (sequence parameter set, picture parameter set). Both types of NALUs must be parsed before a frame can be decoded. When you extract a track with tsMuxer from such a file then tsMuxer will prepend the SPS/PPS NALUs it finds later in the file to the first frame.

mkvmerge on the other hand does not do that. In Matroska the SPS/PPS NALUs are stored in the CodecPrivate element. mkvmerge will only store the SPS/PPS NALUs there and not prepend them to the first frame. This means that upon demuxing the H.264 track from such a Matroska file the resulting H.264 elementary stream won't start with SPS/PPS NALUs either. This is not a bug, this is the intended behavior.

Maybe DGIndexNV cannot cope properly with H.264 tracks which don't start with SPS/PPS NALUs. If so that would be an issue in DGIndexNV.

So far I'm leaning towards »this is not a bug (at least not in MKVToolNix)« unless you can convince me otherwise.

**Comment by dejong12** [comment] 2015-08-23 19:34
Hey there, thanks for investigating the issue. I've uploaded episode.ts on your ftp. Could you see if this file does the same like test.ts?

**Comment by mbunkus** [comment] 2015-08-23 21:01
I've followed the same steps outlined in my first comment. The result is identical: in all three cases there are 68986 frames.

I really fail to see how mkvmerge is supposed to be doing something wrong. Therefore I'm closing the issue again. Sorry.

**Closed by mbunkus** 2015-08-23 21:01 UTC
Labels: app:mkvmerge, v8.3.0
