### ISSUE TITLE
Closed modified file -Message box appears also appears after no modifications done

### ISSUE THREAD

**Issue by Klojum** [mbunkus/mkvtoolnix#1797] opened 2016-10-17 21:22 UTC
I use MKVtoolnix in Ubuntu 14.04.5 LTS 64bit lots of times for checking and changing the contents of various video files. But since a couple of versions, every time I do a quick video file check - without changing or modifying anything - to the video file, and I want to exit the application via the window 'X' method, the "Close modified file" popup messagebox appears and asks for user input: "Cancel" or "Close File". Nothing was modified! By the way, CTRL-Q does not work on v9.5.0 in Ubuntu.

It's already annoying that this pop window appears in the first place, secondly it's even more annoying that the Cancel button has the default focus. It's either using the mouse to click the correct button, or use the keyboard to first type the TAB button and then the ENTER key or SPACE bar to get rid of the message window and close MKVtoolnix finally.

Please doublecheck the exit routines on the MKVtoolnix application, and leave out the unnecessary message windows asking for user input so MKVtoolnix can exit without delay. Thanks in advance.

**Comment by mbunkus** [comment] 2016-10-17 21:28
What exactly do you do with the GUI in such a case? A "quick video file check" can mean a number of things.

**Comment by mbunkus** [comment] 2016-10-17 21:56
BTW, that Ctrl+Q is not working is actually a [bug in Ubuntu/Unity](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619), not in MKVToolNix. To be more precise: uninstall the package `appmenu-qt5` and suddenly you should see the main menu bar appearing (probably after restarting MKVToolNix GUI). As soon as that's the case `Ctrl+Q` and all other accelerators bound to menu entries will magically start working again.

Additionally: in the dialog asking you whether or not to close the file you can also use the keyboard accelerator `Alt+C` or simply `C` for activating the `Close window` function.

**Comment by Klojum** [comment] 2016-10-17 22:38
Hiya, I didn't expect a response that quickly  :-)

About the main problem: checking the contents of the video file with MKVtoolnix for is simply to see which audio streams, subtitles, track names and/or attachments are present inside mkv container files.

For me, change means actual change as in unchecking items in the main window, adding/removing track names, and of course putting in additional subtitles or audio files or changing attachments. But, if I'm just peeking at all input / output / attachments tabs, no changes are made.

Just merely opening a video file, be it via double-clicking a video in Ubuntu's Nautilus or via the "Add files" option inside MKVtoolnix, and then closing it directly, still triggers that "Close modified file" window.

CTRL-Q is not my biggest annoyance. Yes I understand that Alt-C closes the response window, but that means typing two keys... Typing just the 'C' because it is one of the hotkeys is not what I'm accustomed to. When the Close button has the focus, a single ENTER (or Space) is more logical to me.

But ... If there are no changes, that response window (or whatever developers call them today) shouldn't even have to appear. Same like any text editor closes right away when nothing was edited to an opened text file.

After I do a remux and close MKVtoolnix, it closes right away. Closing an unmodified video file should be done the same way.

If there still were changes and MKVtoolnix was closed, there should be not two but three options: Start muxing, Discard changes, and Cancel. Then, either the "Discard changes" or "Cancel" button can have the focus.

That's about the best I can describe it all.  :)
Thanks for the appmenu-qt5 uninstall tip.

**Comment by mbunkus** [comment] 2016-10-18 07:26
> For me, change means actual change as in unchecking items in the main window, adding/removing track names, and of course putting in additional subtitles or audio files or changing attachments. But, if I'm just peeking at all input / output / attachments tabs, no changes are made.

Well, to state something that may be obvious: the GUI's "merge tool" is a tool to merge stuff into Matroska files. This is done by creating configurations how that merge process is supposed to run. These configurations are what the GUI checks for modifications before asking. Any modification to that configuration is taken to be such a modification. This is working as intended.

This is similar to using a word processor such as LibreOffice Writer when all you want to do is check what's currently in the clipboard: start Writer, paste the clipboard content and then exit the application. Writer cannot divine that all you wanted to do is take a quick look at the clipboard content as its main purpose is to create OpenDocument documents. Hence it will ask you if you want to save your changes.

The GUI works the same way. Both types of programs only consider certain states to be "unmodified":

* Right after saving a configuration
* Right after adding it to the job queue
* Right after starting to mux (which is also adding to the job queue but setting the job's state to "start automatically")

Each of these three actions clearly signal to the GUI that the user has finished changing the current configuration to a point where she's finished.

If all you really want to do is to take a peek into what's present in the file then the GUI isn't the right tool for that job. I suggest you consider using e.g. MediaInfo's GUI or mkvinfo's GUI (the latter works on Matroska files only, of course).

Alternatively you can configure the GUI never to ask whether or not you want to save changes by going to "Preferences" → "GUI" and unchecking "Warn before closing modified tabs".

**Closed by mbunkus** 2016-10-18 07:26 UTC
