### ISSUE TITLE
Error starting v14.0.0 - "The version line reported by mkvmerge('') could not be recognized

### ISSUE THREAD

**Issue by henrikhelsingborg** [mbunkus/mkvtoolnix#2061] opened 2017-08-02 12:15 UTC
When I start MKVToolNiv v 14.0.0 I get this:

"The version line reported by mkvmerge('') could not be recognized."

Have tried uninstalling and reinstalling several times. Never had these probems Before upgrading. I run Windows 10 and it is the 64bit installer-version.

**Comment by mbunkus** [comment] 2017-08-02 12:21
This is most likely some program (e.g. your anti virus solution) preventing the execution of the `mkvmerge.exe` binary located in the same path. It's definitely something on your end (machine).

**Comment by henrikhelsingborg** [comment] 2017-08-02 12:24
Ok thanks! I will look further into that. I tried deactivating my antivirus but I still feel than would be the best bet.

**Comment by mbunkus** [comment] 2017-08-02 12:26
Try executing `mkvmerge.exe` from `cmd.exe` and see what happens.

**Comment by henrikhelsingborg** [comment] 2017-08-02 12:35
Found it! 

Apparently my antivirus (Avast) has added trojan protection for certain filetypes, including video-files. I excluded videofiles from that protection, and now things seem to work fine again.

**Comment by mbunkus** [comment] 2017-08-02 12:52
Great!

**Comment by henrikhelsingborg** [comment] 2017-08-02 18:50
It seems I jumped the gun. It only worked once, now the error is back. Anyone know how to solve this?

**Comment by mbunkus** [comment] 2017-08-02 19:15
The error you're seeing does not happen when mkvmerge tries to access a video file, but when the GUI tries to determine if there are problems with your current installation. Right at the start the GUI looks for `mkvmerge.exe`, runs `mkvmerge.exe --version` and tries to parse its output in order to verify that both `mkvmerge.exe` and `mkvtoolnix-gui.exe` are from the same version (I only support using both programs from the same release).

If `mkvmerge.exe` does not produce any output in that second step, then that means that `mkvmerge.exe` was found, that it could be executed (well, the operating system is reporting back that `mkvmerge.exe` was executed; but maybe your A/V solution is blocking the execution and just pretending that it was executed successfully) but that it did not produce any output. Otherwise the error message would be a different one, e.g. "mkvmerge.exe was not found" or "mkvmerge.exe was found but could not be executed"; see [[1]](https://github.com/mbunkus/mkvtoolnix/blob/master/src/mkvtoolnix-gui/util/installation_checker.cpp#L31) and [[2]](https://github.com/mbunkus/mkvtoolnix/blob/master/src/mkvtoolnix-gui/main_window/main_window.cpp#L659).

All I can say to this is that it works just fine for me and thousand of other users. Every time this has come up in the past it was due to the user's anti virus solution messing with the execution somehow. It's definitely not a bug in MKVToolNix, and therefore I'm going to close this bug report. Try defining an exception for the exact path of `mkvmerge.exe` in your anti virus solution, look at the program's log files or maybe at Windows' event viewer, and if that doesn't work and doesn't give you any hints how to fix it, contact the vendor and ask for support.

**Closed by mbunkus** 2017-08-02 19:15 UTC
Labels: os:Windows, res:invalid
