### ISSUE TITLE
mkvtoolnix-gui v8.x crashes on Windows when run from symlink folders

### ISSUE THREAD

**Issue by plastikat** [mbunkus/mkvtoolnix#1433] opened 2015-09-20 07:38 UTC
I use mkvtoolnix 32-bit portable archives, which I download from [fosshub.com](http://www.fosshub.com/MKVToolNix.html) (the place official download page links to). I run Windows 8.1 32-bit.

I unpack the downloaded archive to some folder and I have a *symlink* to this folder at some other location (actually, it's currently a *directory junction*, but the behavior remains the same if I create a true *symbolic link* supported since Windows Vista).

Everything's good when I run **mkvtoolnix-gui** from real folder, but if I run it from symlink folder it crashes with *Microsoft Visual C++ Runtime Error* when I try to add any file. At the same time, the older **mkvmerge gui (mmg)** of the corresponding version runs without errors from any type of location.

**Comment by mbunkus** [comment] 2015-09-20 07:42
This is likely the same issue as #1315, but I'll leave this open for the time being. I don't plan to work on this soon, so please run it from the regular location until it has been fixed.

**Comment by mbunkus** [comment] 2015-09-20 08:09
Hmm, I've decided to give this a try but I cannot reproduce it. I'll need some more details from you, please.

What I've done:

1. Created a new folder C:\symlink-test
2. Unpacked the portable version of 8.4.0 64bit into C:\symlink-test\mkvtoolnix
3. Created a symbolic link with `mklink /D C:\symlink-test\symlink C:\symlink-test\mkvtoolnix`
4. Executed `C:\symlink-test\symlink\mkvtoolnix-gui.exe`

The GUI starts up just fine.

I've then repeated the steps above with a junction instead of a symlink: no problem there either. I've even tried a symlink across devices (symlink on C:, application on D:) without problems.

So can you please give me as many details as you can about your setup, how you execute things, what happens etc?

**Comment by mbunkus** [comment] 2015-09-20 08:45
Dang. Sorry, I misread your report. I thought it was crashing right on startup, and that I cannot reproduce.

I can reproduce the crash when adding the file, though, and this is therefore indeed a duplicate. I'll close this issue in favor of the other one.

**Closed by mbunkus** 2015-09-20 08:45 UTC
Labels: app:MKVToolNix GUI, os:Windows, type:bug, v8.4.0

**Comment by mbunkus** [comment] 2015-09-20 11:25
I've just fixed #1315 and posted new pre-builds there.
