### ISSUE TITLE
Position of preferences window doesn't save.

### ISSUE THREAD

**Issue by savin-msk** [mbunkus/mkvtoolnix#1776] opened 2016-09-01 15:32 UTC
When i open preferences window position of left part of window could not be saved. this bug presenrs for russian language. With english all is OK.
![image](https://cloud.githubusercontent.com/assets/21676987/18173482/69b0692a-7072-11e6-9dff-2f10b5a09ac6.png)

**Comment by mbunkus** [comment] 2016-09-03 07:27
I'm sorry, but I don't really understand what you mean exactly. Please describe in detail which steps you've done and what you would have expected to happen.

Additionally, I've just verified that, even with Russian as the interface language, saving window and splitter positions works just fine for me. What I mean:

* The position of the main window is saved when closing MKVToolNix GUI and restored when starting it.
* The position of the preferences dialog is saved when closing said dialog and restored when opening it again. The position will also be preserved over restarts.
* Within the preferences dialog the slider that determine the size of the tree on the left and the settings on the right is also saved and restored properly.

Therefore I cannot reproduce anything wrong with respect to window and slider positions.

**Comment by savin-msk** [comment] 2016-09-03 14:54
Hi.


When i try to move central line to get visible all text inside tree on the left, frames saved their positoin. After that i made some clicks on different items of tree. After several clicks frames got to position shown on screen.

**Comment by mbunkus** [comment] 2016-09-03 15:02
I see. Well, that's because the Russian translation for some of the items is very long. Therefore the right side's minimum width is pretty high, and the GUI toolkit tries to move the slider before trying to enlarge the whole window.

This is nothing that I'm going to work on; it's basically working as intended. One way to avoid this would be to shorten the Russian translation, but as I don't speak Russian I leave this to my translators.

Sorry.

**Closed by mbunkus** 2016-09-03 15:02 UTC
