### ISSUE TITLE
Issue while remuxing new chapters with a batch

### ISSUE THREAD

**Issue by javanilla** [mbunkus/mkvtoolnix#1141] opened 2015-03-12 21:16 UTC
Hi people!

I made a batch because I have a lot of mkv files to modify, I have copied/paste the command line of mkvmergeGUI, everything works fine.
But when I have a file and I want to replace old chapters by new ones, I can see that the new chapters are remuxed (I see the new titles of my chapters) but the timestamps are those of the OLD chapters.
I don't have that issue when I use mkvmergeGUI, only when I use my batch...
I tried deleting (obviously) "--no-chapters" in my command line, still the same issue...

This is driving me nuts!
Help me get the right timestamps please!

Here is a sample of my batch:
start /b /wait /belownormal /min "#" "mmg\mkvmerge.exe" -o "..\\PROPER\\fileOne.mkv"  "--language" "0:jpn" "--default-track" "0:yes" "--forced-track" "0:no" "--display-dimensions" "0:1440x1080" "--language" "1:jpn" "--default-track" "1:yes" "--forced-track" "1:no" "--language" "2:fre" "--default-track" "2:no" "--forced-track" "2:no" "--language" "5:mis" "--track-name" "5:Ghost" "--default-track" "5:no" "--forced-track" "5:no" "-a" "1,2" "-d" "0" "-s" "5" "--attachments" "1,2" "-T" "--no-global-tags" "(" "fileOne.mkv" ")" "--language" "0:fre" "--track-name" "0:ASS" "--default-track" "0:yes" "--forced-track" "0:no" "-s" "0" "-D" "-A" "-T" "--no-global-tags" "(" "subtitles\\fileOne.ass" ")" "--language" "0:fre" "--track-name" "0:SRT" "--forced-track" "0:no" "-s" "0" "-D" "-A" "-T" "--no-global-tags" "(" "subtitles\\fileOne.srt" ")" "--track-order" "0:0,0:1,0:2,1:0,2:0,0:5" "--title" "Episode One" "--chapter-language" "fre" "--chapters" "chapters\\fileOne_chapters.xml"

.
EDIT: got it working!! seems I had to keep both "--no-chapters" in the command line, weird huh?!

**Comment by mbunkus** [comment] 2015-03-13 08:52
My guess is that your new chapters use the same ChapterUID elements as the chapters in one (or both) of the source files. The same ChapterUID means that the chapter entries belong to the very same chapter, and therefore mkvmerge merges such entries: their combined start timestamp will be the minimum of all the start timestamps of the individual entries; dito for their end timestamps.

So in order to avoid something like that use unique ChapterUID elements (that's what the »U« in »UID« stands for, after all: Unique ID). Or don't use ChapterUID elements in your XML file at all; that way mkvmerge will assign random ones itself.

As for needing `--no-chapters` for both input files: Well… mkvmerge will keep as much content as possible by default unless you tell it otherwise.

Anyway, this is not a bug; I'm therefore closing this issue.

**Closed by mbunkus** 2015-03-13 08:52 UTC
