### ISSUE TITLE
Muted audio track when muxed

### ISSUE THREAD

**Issue by rootsandculture** [mbunkus/mkvtoolnix#1524] opened 2015-11-28 15:24 UTC
Hi, I have an BD with 2 audio tracks, Original Japanese and Commentary in English. I selected keep only the original Japanese and it is muted when muxed. It appears as option for selecting in VLC but has no audio.

Here's the info.
[Roots.txt](https://github.com/mbunkus/mkvtoolnix/files/46364/Roots.txt)

Any ideas?

**Comment by mbunkus** [comment] 2015-11-28 15:48
I cannot really say anything to what might have gone wrong here without access to such a file (the source, that is, not the Matroska file). Can you please upload the first 100 or 200 MB of the corresponding .m2ts file to [my FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server), please, so that I can take a look at it? You should make sure that there's actually something to hear within the range you're uploading.

**Comment by rootsandculture** [comment] 2015-11-28 16:34
I created a Roots folder in your FTP.

**Comment by mbunkus** [comment] 2015-11-28 19:02
I cannot really reproduce this. When muxing only the first audio track (the PCM one) VLC does play it. Note that the first 20 seconds of the movie are completely silent, even in the .m2ts file – that's not due to mkvmerge.

VLC does play the audio track back choppily. But that's most likely VLC's fault. I've checked the timestamps generated by mkvmerge for the audio track as well as the header data and they're consistent and correct for a mono PCM audio track at 48 kHz sampling frequency with 24bits/sample.

So you should open a bug report with VLC for the choppy playback.

I'm closing this as works for me.

**Closed by mbunkus** 2015-11-28 19:02 UTC

**Comment by remuxer32** [comment] 2015-11-28 19:30
**@rootsandculture** 

Let me advise you something. 

Try to rip your Blu-ray Disc with MakeMKV. MakeMKV is a program that allows you to copy your DVD or BD into Matroska. You can select your favourite audio tracks, subtitles etc. If, after muxing completion, your audio track still is muted then it means (99%) a bug in VLC. You can also try to play your audio track with other players (e.g. Media Player Classic Home Cinema); maybe the behaviour will be different.

Good luck.

**Comment by rootsandculture** [comment] 2015-11-28 19:56
But the VLC plays ok the original .m2ts. It happens after converting it to .mkv.

**Comment by mbunkus** [comment] 2015-11-28 19:57
Still doesn't mean the bug isn't in VLC; it can be in its Matroska support. And like I said: my VLC does play the track.

**Comment by rootsandculture** [comment] 2015-11-28 20:05
@remuxer32 Tried with MakeMKV and and works right, the audio track plays ok.

**Comment by remuxer32** [comment] 2015-11-28 20:33
**@rootsandculture**

I'm glad I helped you. In my humble opinion MakeMKV is the best tool to rip DVDs or Blu-rays, therefore if you need to rip your disc then always do that with MakeMKV. But if you need to merge a movie which was divided into two discs (e.g. »The Lord of the Rings« — Extended Edition) then you can try mkvmerge first or even use MakeMKV in order to create two .mkv files, but MakeMKV doesn't contain an option for merging files so you would have to use mkmerge for that, anyway.

**Comment by ndjamena** [comment] 2015-11-28 22:47
The few times I've used MKVMerge directly on a Blu Ray with LPCM, the PCM turned out to be "Big Endian", which basically means the bytes for each sample are ordered backwards compared to a file with the "Little Endian" LPCM used in common WAV files.

The current version of MPC-HC distorts playback of big endian PCM, but the nightly version of VLC I'm using at the moment plays it back perfectly.

When MakeMKV encounters Big Endian LPCM, it automatically converts it to Little Endian LPCM and I doubt a player exists that would have a problem with that.

**Comment by rootsandculture** [comment] 2015-12-19 15:00
I'm uploading another .m2ts with similar problem (on your FTP under ''Roots'' folder). I can play fine the original .m2ts file, but after making a .mkv with selected audio tracks, the audio is muted in the new file.

**Comment by ndjamena** [comment] 2015-12-19 15:04
+ Codec ID: A_PCM/INT/BIG

THAT is your problem.  It's Big Endian PCM which many players can't handle properly in MKV.  The problem has nothing to do with MKVMerge, if you want it fixed file bug reports with your media players.

**Comment by rootsandculture** [comment] 2015-12-19 15:16
Ok, sorry. Which nighty version are you using, latest "vlc-3.0.0-git-20151219-0402" doesn't plays it either.

**Comment by ndjamena** [comment] 2015-12-19 15:23
Maybe I got it backwards.  MPC-HC is playing it fine.

I can't even get VLC to work anymore...  I wonder if the VideoLan President found a way to nuke my system...?  (Or maybe it was that last Windows 10 update)
