### ISSUE TITLE
.sub aren't registering as being added

### ISSUE THREAD

**Issue by TwistedFaith84** [mbunkus/mkvtoolnix#1427] opened 2015-09-12 05:49 UTC
Ive been using version 8.3.0 for a little bit and through I am very pleased that when merging files it does now support various SUBTITLES files; lately I've noticed that when trying to merge a .sub file to a video file the program shows that it was added in the files listed but doesn't appear to have actually been added cause it doesn't show up on the tracks listed. I've been using mkvtoonix for a long time and I know that previous versions did add the . sub files properly and it work correctly when added.

**Comment by mbunkus** [comment] 2015-09-13 06:03
Thanks for the report. This is probably something limited to that file. I'll need the file itself in order to find the cause. Can you please upload it to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server)? Thanks.

**Comment by TwistedFaith84** [comment] 2015-09-14 00:18
Yea I'll upload the file  thats no problem. But I have this problem with a few .sub files not just one.

**Comment by mbunkus** [comment] 2015-09-18 07:13
You haven't uploaded such a file yet, have you?

**Comment by TwistedFaith84** [comment] 2015-09-19 20:23
No sorry I've been a little busy I'll upload it soon-ish

**Comment by TwistedFaith84** [comment] 2015-09-29 07:37
Hey sorry it's been a while I've been pretty busy. I looked for the .sub file and apparently I must have deleted them. so if and when it happens to me again I'll let you know and I'll post the files to your FTP Server

**Comment by mbunkus** [comment] 2015-09-29 07:42
Alright, I'll close the issue for the time being then.

**Closed by mbunkus** 2015-09-29 07:42 UTC
