### ISSUE TITLE
XMedia Recode

### ISSUE THREAD

**Issue by mkvGuy** [mbunkus/mkvtoolnix#1770] opened 2016-08-22 01:50 UTC
After using XMedia Recode to change audio track, the resulting file's header cannot be edited in MKVtoolnix unless I remux first using MKVtoolnix .  If I try it seems to delete all entries in the header

**Comment by mbunkus** [comment] 2016-08-22 06:42
How did you determine that the track headers have been deleted afterwards? If you re-open the file in the header editor after having modified it does the header editor still show the track headers?

**Comment by mkvGuy** [comment] 2016-08-26 20:43
still shows them, but they are blank

**Comment by mbunkus** [comment] 2016-08-29 08:10
Which program did you use to determine that "they are blank"? Please use mkvextract to verify that the tracks really don't contain any content anymore.

**Comment by mbunkus** [comment] 2016-09-03 07:29
I'm pretty sure that this is not a bug in MKVToolNix but in one of the programs you're using. See [this wiki article](https://github.com/mbunkus/mkvtoolnix/wiki/All-tracks-vanished-after-mkvpropedit,-the-header-or-chapter-editors) for what I mean. I'm going to close this issue for the time being. If you can show me that there's really something wrong I'll be happy to re-open it.

**Closed by mbunkus** 2016-09-03 07:29 UTC

**Comment by mkvGuy** [comment] 2016-10-03 17:05
I used MKVToolsnix header editor to determine this
