### ISSUE TITLE
Private tags written to more than one stream

### ISSUE THREAD

**Issue by kashmirix** [mbunkus/mkvtoolnix#1681] opened 2016-05-03 15:28 UTC
Since around 8.0.0, MKVToolNix writes private tags to every file it creates:

```
DURATION                    : 01:55:25.856000000
NUMBER_OF_FRAMES            : 216433
NUMBER_OF_BYTES             : 554068480
_STATISTICS_WRITING_APP     : mkvmerge v9.1.0 ('Little Earthquakes') 64bit
_STATISTICS_WRITING_DATE_UT : 2016-05-03 15:02:22
_STATISTICS_TAGS            : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

```

Since around 9.1.0, when merging tracks from two or more files, private tags are written multiple times, now not only under segment information but now under track information. This mostly occurs for audio and/or video tracks that are being added from other files.

As a result, the same private tags now occur several times in a single file. This is well visible in MediaInfo.

The bug might not cause adverse effects on playback but might be against specs and might increase file head section size. It is also unsightly :)

I am not an IT pro so don't ask me too complex questions - thanks!

**Comment by mkver** [comment] 2016-05-03 17:39
I'm not Moritz Bunkus (the developer of MkvToolNix), but I'll answer nevertheless. MkvToolNix writes these infos in two places: In the header in "segment info"-fields and as tags for each track at the end of the file. You can see this yourself by using mkvinfo with the option to display all elements. That the statistics-tag needs to be per track is completely obvious when you consider that things like duration and number of frames differ between tracks. The "writing app" and "writing date" fields are indeed stored more than once if you use mkvtoolnix and stick to the default settings; but this serves a purpose: It allows you to determine whether the tags are up to date. More on this can be found in the [wiki article](https://github.com/mbunkus/mkvtoolnix/wiki/Automatic-tag-generation).
Although I haven't read the relevant part of the specification, I am certain that mkvtoolnix does not break them.
If any program has a bug here, it seems to be mediainfo for its erratic behaviour: Sometimes it only displays the statistic tags only under the "General" section and then it picks the number of frames from one track (often an audio track (maybe always the last one? I know examples in which it showed the number of frames of a subtitle track under the "General" label and in this situation this was the last track)) and not the video track. And sometimes it shows statistics not only under the "General", but also for an individual track.

**Comment by mbunkus** [comment] 2016-05-03 19:02
Just like mkver I highly suspect that you're misinterpreting MediaInfo's output or that MediaInfo is buggy wrt. the handling of those tags. If you want me to take a look at such a file then please upload one to [my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). Otherwise I'll close the bug as invalid, especially as I cannot reproduce a problem myself.

**Comment by kashmirix** [comment] 2016-05-03 19:05
Hi @mkver , thanks for clarification. The Wiki link helped a lot. I believe statistic tags were only written for the entire file, not for individual tracks, until recently. Or at least MediaInfo did not show them before. Hence my surprise.

That said, the bug report might indeed be invalid. Thanks for your responses anyway.

**Comment by mbunkus** [comment] 2016-05-03 19:07
Alright, then I'll close this issue for now.

**Closed by mbunkus** 2016-05-03 19:07 UTC
