### ISSUE TITLE
Running ./drake inside pBuilder fails

### ISSUE THREAD

**Issue by darealshinji** [mbunkus/mkvtoolnix#1189] opened 2015-05-11 07:09 UTC
I want to build mkvtoolnix from source for Ubuntu. But ./drake will fail inside a pbuilder chroot:
```
./drake --trace apps:mkvinfo apps:mmg apps:mkvtoolnix-gui
rake aborted!
invalid byte sequence in US-ASCII
/tmp/buildd/mkvtoolnix-7.9.0/Rakefile:854:in `match'
/tmp/buildd/mkvtoolnix-7.9.0/Rakefile:854:in `block (3 levels) in <top (required)>'
/tmp/buildd/mkvtoolnix-7.9.0/Rakefile:854:in `each'
/tmp/buildd/mkvtoolnix-7.9.0/Rakefile:854:in `any?'
/tmp/buildd/mkvtoolnix-7.9.0/Rakefile:854:in `block (2 levels) in <top (required)>'
/tmp/buildd/mkvtoolnix-7.9.0/Rakefile:853:in `select'
/tmp/buildd/mkvtoolnix-7.9.0/Rakefile:853:in `block in <top (required)>'
/tmp/buildd/mkvtoolnix-7.9.0/Rakefile:852:in `each'
/tmp/buildd/mkvtoolnix-7.9.0/Rakefile:852:in `<top (required)>'
/tmp/buildd/mkvtoolnix-7.9.0/rake.d/vendor/drake-0.9.2.0.3.1/lib/rake/rake_module.rb:25:in `load'
/tmp/buildd/mkvtoolnix-7.9.0/rake.d/vendor/drake-0.9.2.0.3.1/lib/rake/rake_module.rb:25:in `load_rakefile'
/tmp/buildd/mkvtoolnix-7.9.0/rake.d/vendor/drake-0.9.2.0.3.1/lib/rake/application.rb:511:in `raw_load_rakefile'
/tmp/buildd/mkvtoolnix-7.9.0/rake.d/vendor/drake-0.9.2.0.3.1/lib/rake/application.rb:78:in `block in load_rakefile'
/tmp/buildd/mkvtoolnix-7.9.0/rake.d/vendor/drake-0.9.2.0.3.1/lib/rake/application.rb:129:in `standard_exception_handling'
/tmp/buildd/mkvtoolnix-7.9.0/rake.d/vendor/drake-0.9.2.0.3.1/lib/rake/application.rb:77:in `load_rakefile'
/tmp/buildd/mkvtoolnix-7.9.0/rake.d/vendor/drake-0.9.2.0.3.1/lib/rake/application.rb:61:in `block in run'
/tmp/buildd/mkvtoolnix-7.9.0/rake.d/vendor/drake-0.9.2.0.3.1/lib/rake/application.rb:129:in `standard_exception_handling'
/tmp/buildd/mkvtoolnix-7.9.0/rake.d/vendor/drake-0.9.2.0.3.1/lib/rake/application.rb:59:in `run'
./drake:39:in `<main>'
make[1]: *** [override_dh_auto_configure] Error 1
make[1]: Leaving directory `/tmp/buildd/mkvtoolnix-7.9.0'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```
This doesn't happen if I build it directly without using pbuilder. But I want to add this package to my PPA on Launchpad and LP uses pbuilder so the builds there fail too.

**Comment by mbunkus** [comment] 2015-05-11 07:17
This happens if the environment doesn't contain a locale setting with UTF-8 as the encoding (e.g. `LC_CTYPE=en_US.UTF-8`. I thought I had fixed this on Saturday already, but it looks like I committed another workaround…

As a workaround you can try setting the locale before running drake.

**Closed** 2015-05-11 16:22 UTC
Labels: bug, v7.9.0

**Comment by mbunkus** [comment] 2015-05-11 16:26
I'd appreciate it if you could give it a try. I was able to reproduce it with `LC_ALL=C ./drake`, and the commit fixes that; it should fix the situation with pBuilder, too.

If not just post here and I'll re-open the issue.

Thanks for the report.

**Comment by darealshinji** [comment] 2015-05-12 08:29
Yes, now it builds. Thanks.

**Comment by mbunkus** [comment] 2016-04-11 20:00
Woah, those two commits are definitely attributed to the wrong issue.
