### ISSUE TITLE
Auto-generation of Chapters of 300s doesn't work

### ISSUE THREAD

**Issue by eleanor-bron** [mbunkus/mkvtoolnix#1693] opened 2016-05-14 22:48 UTC
Auto-generation of chapters of duration "300s" doesn't create any chapters.

1) Go to output tab
2) Under "chapters", select "chapters in fixed intervals"
3) enter "300s" in "Interval" field

Output does not create any chapters!

Tested with others values, for example "400s" and it creates the chapters fine.

**Comment by mbunkus** [comment] 2016-05-15 09:07
There was a bug in v9.0.0 that caused problems if too many chapters were generated. That had been fixed in v9.0.1, and I cannot reproduce this issue at the moment (it works just fine for me here). Which version are you using? If it's not 9.1.0 then please upgrade to 9.1.0 and try again.

**Comment by mbunkus** [comment] 2016-05-15 09:09
Ooops, scratch that, after playing around with it some more I can actually reproduce it. Thanks for the report.

**Closed** 2016-05-15 10:07 UTC
Labels: app:mkvmerge, os:all, type:bug, v9.1.0
