### ISSUE TITLE
New GUI: merge tool: the GUI asks for confirmation before closing or quitting even if a file hasn't been modified at all

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1241] opened 2015-06-08 02:47 UTC
Watch this film please: https://youtu.be/dZnTOW2Ejts

About situation number 3: as you can see I removed all files from the field. I'm not sure if the GUI should ask for confirmation in such cases as there are no files to modify and which haven't been modified because of removing them from the field, of course. I'm interested in your opinion. Thanks.

**Comment by mbunkus** [comment] 2015-06-08 18:58
The functionality »warn before closing a tab that's been changed« means that if the merge settings have been changed this will apply. And as soon as you add a file this is the case; the settings have been changed: from no source file to one source file. Working exactly as intended.

It's not about the source file you've added, it's about the merge settings. The _settings_ have been changed.

**Comment by mbunkus** [comment] 2015-06-08 18:59
Oh, and in situation 3 the output file name has been set, therefore the settings have been changed versus completely blank settings.

**Closed by mbunkus** 2015-06-08 18:58 UTC

**Comment by remuxer32** [comment] 2015-06-08 19:48
Thank you for your clarification, Mosu. Now I understand precisely. It was my mistake; I thought it's about the source file(s). Now I know I was wrong. I'm sorry for confusion.
