### ISSUE TITLE
Cannot merge two mkvs created with handbrake

### ISSUE THREAD

**Issue by Krawk** [mbunkus/mkvtoolnix#1561] opened 2016-01-05 04:43 UTC
Using the toolnix gui 8.7.0/64-bit, Windows 7/64
Original Source - Dinotopia tv miniseries movie dvds.

When I try to merge two mkv files that were coded with Handbrake, the second file is all garbage video and no chapters.

Original sources are identical in every aspect, and the encode settings are exactly identical in handbrake. Encoding in handbrake to h264, 2-pass encoding, "very slow" optimise video - no bitrate specified.

When I add each file in mkvtoolnix, each one is showing the correct audio and video codecs, the correct number of chapters in each file (file 1 is 32 chapers, file 2 is 18 chapters.) When I click Mux to create a merged file, I get a new file with correct length and size, but the second portion of the video no longer has chapter marks. Furthermore, when you click past chapter 32 to get to what would be the second video, the video is a scrambled mess with nothing recognizable.
If Handbrake is using VBR should it matter from chapter to chapter? If it is a fixed rate, the resolution is identical in both files so the rate should be the same.

Why am I doing this? Chapter 32 on disc 1 and Chapter 1 on disc 2 are exactly identical, so I asked handbrake to skip chapter 1 on disc 2.

**Comment by mbunkus** [comment] 2016-01-05 11:38
The chapters is probably due to a stupid design decision in HandBrake if I remember correctly.

Matroska's chapter system contains a "unique ID" property for each chapter. These are intended so that players and remuxers can determine which chapter entries belong together logically. For example, if you have one big file with chapters and split it with mkvmerge in the middle of a chapter then mkvmerge will include that chapter once in each file and just the start and end time accordingly. Logically this is still a single chapter, though; if you use mkvmerge and append the split files together then mkvmerge will recognize those two chapters being one and the same and re-create a single chapter from them that encompasses the duration of both prior entries.

HandBrake on the other hand uses sequential numbers for its chapters, and those numbers start at 1 for each file. The result is that mkvmerge thinks that chapter 1 from file 1 and chapter 1 from file 2 are indeed supposed to be the same chapter.

You can verify this is the case with e.g. the GUI's chapter editor. In it you can also fix those UIDs manually by assigning random numbers to each (or at least to make sure that no two chapters in the two files have the same UID). Then save them and merge & append again.

About the video corruption: I cannot say anything about that at the moment. I'll need access to the two source files if you want me to take a look at; you can upload the files [to my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server), for example. My gut feeling is that even though you think you've used the same encoder settings they're different enough so that decoding the second half with the settings of the first half is simply not possible.

**Comment by Krawk** [comment] 2016-01-06 05:20
Thanks for the response. 
An easier solution for me would be if makemkv were to be able to rip with specified chapters as disc 2 chapter 1 says "HEAD" rather than "1" - DvdFab has such a feature but very often when it creates a file, at one of its chapter marks the video macroblocks. That happens even when using "Mkv Passthru" as the rip option.

The first file is very large and will take some time to process as my up speed is locked a 1Mbps. Will let ya know.

**Comment by Krawk** [comment] 2016-01-06 18:45
So you will need the two files coded with handbrake, correct? That being the case, only talking about 2Gb which is not overly terrible. You can digest Rar files of course?

**Comment by mbunkus** [comment] 2016-01-06 18:46
I'll need two files for which the issue happens, yes. Any archiver is fine including RAR.

**Comment by mbunkus** [comment] 2016-01-16 19:51
So, are you going to upload those files? Otherwise I'll close this issue. I've already explained the likely reasons for how the chapters are handled, and I doubt there's anything I can do about the video tracks anyway.

**Comment by Krawk** [comment] 2016-01-16 23:22
I will upload the file yes, but have to recreate the files from scratch, including re-doing them with Handbrake.

**Comment by Krawk** [comment] 2016-01-18 01:09
I am recreating the files tonight and will archive and begin the upload process tomorrow. It will take some time, perhaps a couple of days but you will see progress.

**Comment by sneaker2** [comment] 2016-01-18 18:49
Don't bother, I have reproduced it locally and uploaded samples to the ftp server that show the chapter problem.

About the video becoming garbage problem:
As Mosu said, that cannot be fixed by mkvtoolnix. You can avoid that problem in the future by inserting "stitchable=1" into the "Extra Options" field in HandBrake's video tab when encoding using x264.

**Comment by Krawk** [comment] 2016-01-19 01:00
Thanks sneaker2 for that. So should one always use stitchable=1 on every video then just because ya never know what the future may bring?

As you have uploaded samples, any suspicion on what causes the video corruption?

**Comment by sneaker2** [comment] 2016-01-19 05:44
An H.264  decoder needs certain headers to decode a given, H.264 compressed frame. When you encode a video using x264 these headers will be valid for all of the file. When HandBrake muxes the H.264 stream into the mkv container it takes the H.264 header and puts it into an mkv element designed to store codec headers that are valid for the complete track. The problem is that when you encode a second file x264 might decide on a slightly different header even if the settings are seemingly identical to the first file in order to save a few bytes (think 0.00x%). Unfortunately, mkv can only store one of these headers into the element designed to store the codec headers. In your case those were the headers of the first file. Now, as long as you are seeking in the first part of your appended file your H.264 decoder had the correct headers and thus the playback was fine. When you tried to seek into the second part it still tried to use the headers of the first part which - of course - does not work. Playback becomes garbage.
The solution was to use the "stitchable=1" option. That tells x264 to not optimize the headers for every movie but instead try to use the same headers for every file. This will make all output files appendable ("stitchable") unless you try to use settings that are very different. As I said this option only increases filesize by maybe 0.00x% and has no other negative drawbacks so you can activate it for every encode you do.

**Comment by mbunkus** [comment] 2016-01-19 12:03
Thanks for the sample files, @sneaker2. The chapters do indeed use the same UIDs. This is, as I've stated before, a design bug in HandBrake and not a bug in mkvmerge.

The issue with appending files isn't a bug in mkvmerge either as sneaker2 has explained.

I'm therefore closing this issue.

**Comment by mbunkus** [comment] 2016-01-19 16:37
I've implemented a workaround for such files created by HandBrake regarding the handling of chapters.

**Closed by mbunkus** 2016-01-19 16:37 UTC
Labels: app:mkvmerge, os:all, type:enhancement, v8.8.0

**Comment by Krawk** [comment] 2016-01-19 17:26
Thank you ever so kindly sir!

**Comment by Krawk** [comment] 2016-01-19 20:52
So have you created a workaround or have you basically fixed Handbrake's method of chaptering to standard?

**Comment by mbunkus** [comment] 2016-01-19 21:03
If the file was created by HandBrake then mkvmerge will simply ignore the existing edition and chapter UIDs and assign new ones. Therefore I've created a workaround in mkvmerge for HandBrake's behavior; I haven't fixed HandBrake itself (I'm not the HandBrake author, and based on my past experience with him/them I have no intention of submitting a patch to them to fix their program).

**Comment by Krawk** [comment] 2016-01-19 23:58
Still much appreciated. Was mostly asking if I were to go to chapter editor and essentially just remux the file if it would rewrite the chapter table, but I understand your answer to be no. You have a "contribute $$" link somewhere?

**Comment by mbunkus** [comment] 2016-01-20 08:38
The chapter editor hasn't been changed, that's correct. Only mkvmerge itself. So starting the GUI, adding a file created by HandBrake and starting muxing will do the job.

There are "donate" buttons at the top of nearly each page on [the MKVToolNix homepage](https://mkvtoolnix.download/).
