### ISSUE TITLE
chapter name template is not localized properly

### ISSUE THREAD

**Issue by bastik-tor** [mbunkus/mkvtoolnix#1307] opened 2015-06-27 13:23 UTC
Starting conditions: Windows 7 64 bit (German) with 8.0.0 was set to interface language English.

Installing 8.1.0 shows "Kapitel <NUM>" while the rest is English. Creating new chapters uses the German string, which was not what I had expected. I wouldn't have opened an issue if "Chapter <NUM>" would be the default string and user are expected to change it, should they desire something else to be used.

German does not appear to be universally understood around the globe, so having it as the default string, doesn't seem right.

I said that I run a German version of Windows in case that it derives the template name from that clue. I tried other languages for the interface of MKVtoolnixGUI, but the string does not change. (I am aware that I can change it.)

So I would either change it to English by default or be something translators can localize.

**Comment by mbunkus** [comment] 2015-06-27 13:28
The chapter name template can be set in the preferences. If that setting is not present in the settings file when the application starts then the default is assumed. The default depends on the user locale of the GUI at that point, and this is probably German due to your OS being German.

The default is already localized according to your OS; it isn't hardcoded in German. The problem is the order in which saved settings are applied.

I don't think I'll invest any time in this at the moment.

**Comment by mbunkus** [comment] 2015-06-27 13:33
To make this a bit clearer. The interface language stored in the settings should be applied before the default is generated. At the moment the order in which things happen is:

1. The GUI is started and set to the default interface language derived from the operating system's language. In your case: German.
2. The settings are read. During this procedure the settings class sees that there's no entry for the chapter name template yet and uses a localized default of `gettext("Chapter <NUM>")`. At this point the currently active locale is the one from 1.; the one derived from the operating system's language; in your case: German.
3. After the settings have been read the user interface language read from the settings in 2. is applied; in your case: English. At this point the chapter name template has already been initialized, though.

Unfortunately this is a pretty bad violation of the class design and will require some dirty workarounds.

**Comment by bastik-tor** [comment] 2015-06-27 13:39
> The default is already localized according to your OS; it isn't hardcoded in German

For me, this ticket turned irrelevant with this answer.

The string is set to the OS language, which could be the same as the one of the GUI, and it can be changed by the user and it is not changed by the application itself again.

To me it seems like it would not be an issue for most users to set this string once.

**Comment by mbunkus** [comment] 2015-06-27 13:42
I agree that not a lot of users will be affected.

There is a possible fix that isn't really dirty: delay applying that default value until it is actually required (e.g. used in the chapter editor or when the user opens the preferences dialog for the first time).

This won't help users who've run 8.1.0 or anything later until the fix has been implemented, of course, but it should be the right thing to do. Therefore I'll leave the issue open, but it won't have that high a priority for me.

**Comment by mbunkus** [comment] 2015-06-28 08:18
I've decided not to attempt to fix this for the time being.

**Closed by mbunkus** 2015-06-28 08:18 UTC
Labels: app:MKVToolNix GUI, type:bug, v8.1.0
