### ISSUE TITLE
Positive delay value doesn't take effect in mka

### ISSUE THREAD

**Issue by midgetspy** [mbunkus/mkvtoolnix#2174] opened 2017-12-14 05:39 UTC
I'm using MKVToolNix v18.0.0 on Windows 7 (64-bit). I originally found this problem on my old v8.0.0 install.

To reproduce:

Create a new multiplexer containing a single TrueHD audio track and multiplex it into an MKA (#&#xfeff;1). Change the delay to `-1000` (or `--sync 0:-1000`) and create a second MKA (#&#xfeff;2). Change the delay to `1000` (or `--sync 0:1000`) and create a third MKA (#&#xfeff;3).

I expect that when I play MKA #&#xfeff;2 the audio should be 1 second earlier than in MKA #&#xfeff;1, and when I play MKA #&#xfeff;3 the audio should be 1 second later than in MKA #&#xfeff;1.

MKA #&#xfeff;2 works as expected but MKA #&#xfeff;3 plays identically to MKA #&#xfeff;1, the audio is not delayed at all. I've tried playback in MPC-HC and Kodi and seen the same thing. I have not tested with audio streams other than Dolby TrueHD.

I've uploaded my MKA #&#xfeff;1 as "issue 2174.mka" to your SFTP server. If you open it and remux with positive delay you can see the problem.

**Comment by midgetspy** [comment] 2017-12-14 05:46
Worth noting: If I do this same test but include a video stream as well then it all works as expected (generates 3 MKVs and the audio is delayed appropriately in all 3).

**Comment by mkver** [comment] 2017-12-14 07:19
This is not a bug; this behaviour results from ffmpeg's handling of time (ffmpeg is indirectly used by both MPC-HC (via LAVFilters) and Kodi). ffmpeg normalizes the timeline so that playback always starts at zero (regardless of the internally used Matroska timestamps) while maintaining sync of the tracks (i.e. they are offset by the same amount, not so that every track begins at zero; this is the reason it works as expected when using a video track). This might seem strange from a Matroska perspective (for which it would be "natural"* to insert a second of silence at the beginning), but ffmpeg supports many more formats. Some of these formats usually don't start at zero (think of transport streams -- this is the format that digital TV uses; and if you just tune into a channel (or watch a recording), the timestamps usually don't begin at zero).
*: This is of course up for debate.

**Comment by midgetspy** [comment] 2017-12-14 07:57
Hm, interesting, thanks for the explanation @mkver. I guess that makes sense in the context of playing the audio track alone.

This is a little bit off topic but since it sounds like you have some domain knowledge here I'd like to pick your brain a minute if you don't mind.

My original use case was playing an MKV and specifying the audio track from an MKA (which had a delay). I expected the same results whether the video and audio came from the same MKV or whether they came from separate containers but found that when the audio was separate the delay wasn't respected (in both Kodi and MPC-HC).

Based on your explanation above it sounds like there must be some difference in how Kodi/MPC-HC use ffmpeg when the audio and video are in separate containers vs. when they are in the same container. In that case it sounds like this is simply a bug in MPC-HC/Kodi's handling of external audio files? I can understand how it'd happen, they probably let ffmpeg demux each container separately and if it normalizes the audio timeline at that point then it's game over. I guess if there was a way to find the original timestamp of the first frame they could apply the delay themselves...

I'll move this discussion to the Kodi/MPC-HC issue trackers, thanks for your time.

**Comment by mkver** [comment] 2017-12-14 10:32
Yes, if they are in separate containers, they are normalized separately. You should also note that ffmpeg is smart enough not to normalize srt subtitles.
I also know a workaround for you problem: Instead of muxing only the audio track (with the right delay) into the mka, you also mux a srt subtitle track that starts at 0:00 (has a packet at 0:00). Then MPC-HC plays the audio with the intended delay. But beware: Do not seek into the time where there is no audio! It seems MPC-HC can handle the inexistence of audio at the start, but not after a seek. MPC-HC freezes if you seek into the part of the file without audio. (But if you seek to the absolute beginning, everything's fine. As I said: MPC-HC can handle the inexistence of audio at the start.)

**Comment by mbunkus** [comment] 2017-12-14 10:50
As @mkver has explained very well, this is not a bug in mkvmerge. I'll close the issue.

**Closed by mbunkus** 2017-12-14 10:50 UTC
