### ISSUE TITLE
Mistakes in 8.7 versus

### ISSUE THREAD

**Issue by Alexx55** [mbunkus/mkvtoolnix#1556] opened 2016-01-01 06:58 UTC
The portable version does not work Plug and Play and the output is not created a new file and its shortcut.

**Comment by mbunkus** [comment] 2016-01-01 09:29
I really don't understand what you're trying to say. I've just downloaded both portable versions and both work just fine here. So please describe what you're doing, what is happening and what you expected to happen in more detail and in better English because your sentences don't really make sense. Maybe ask someone else to translate for you if your English isn't that good.

**Comment by r0lZ** [comment] 2016-01-03 23:44
Alexx55 is right.  MkvMerge 8.7.0 for Windows 32-bit (from the standalone portable version and the installer) doesn't work at all.

If you mkvtoolnix-gui.exe, and then add a file (say video.h264), it tells that it "cannot find mkvmerge".

And if you launch mlvmerge from the command line, it shows the list of multiplexers it will use for each stream, then exits directly without having muxed anything and without any error message.

That may be a bug of the Windows build only.  And I have not checked the 64-bit versions.

There is no need of an example.  All tests I did have the same problem, extremely easy to reproduce (under Windows).

**Comment by r0lZ** [comment] 2016-01-03 23:50
I forgot to say that it is sufficient to replace the exes with v8.6.1 and everything works fine.  It's clearly a bug introduced with v8.7.

(Also, above, I should have written "If you *launch* mkvtoolnix-gui.exe,...")

**Comment by mbunkus** [comment] 2016-01-04 17:27
I cannot reproduce such a behavior. Therefore I'm pretty sure that it depends on the file you're adding. Can you please upload one such file to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server) so that I can evaluate this further?

**Comment by mbunkus** [comment] 2016-01-04 18:32
Can you two please give one of my [new pre-builds](https://mkvtoolnix.download/windows/pre/) a try? It's entirely possible that this issue has already been fixed since release the release of 8.7.0 and is really a duplicate of #1559.

**Comment by r0lZ** [comment] 2016-01-04 19:49
Oh, well, I have just re-downloaded v8.7.0 32-bit portable final from fosshub, and I can't reproduce the problem any more.  I don't understand why.  I have then re-tested the same version from the previous 7Z file downloaded from the same site, and it works well too!  I'm confused!  Since the tests that failed, I have rebooted the PC.  Therefore, I suppose that something has changed in my computer that explains the difference.  The question is what ?!

Anyway, I have tested also the mkvtoolnix-32bit-8.7.0-build20160103-01105-9a21bde pre-build, just to be sure, and of course it works well too.

When it failed, I was adding a HD 1080p video file created with x264 (AVC high@L4.1) by me, and I use always the same encoder settings, that have never caused problems.  As I said, it was possible to mux that file without problem with v8.6.1.  Also, the strange error message "can't find mkvmerge" was happening immediately after adding any file to mkvtoolnix-gui, including when the gui is launched from the command line with the @file.txt syntax to mux that video file and some audio and subtitle files.  It's the procedure used by my program BD3D2MK3D and it has always worked well.  Since there was no problem with v8.6.1 (and before the reboot), I don't think it's related to the type of stream.  And I have mkvtoolnix portable fully installed in a directory, and MkvMerge only (with the data directory) in the folder used by BD3D2MK3D.  Both were not working at the same time.

My conclusion is that here is something strange with v8.7, happening only in some precise circumstances, but I don't know how to determine that circumstances.  If I can reproduce the problem, I'll let you know.  In the meantime, I can give you a short h264 sample if you wish, but I don't think that will help.

I think you can close this bug, and I'll reopen it if it happens again.

**Comment by mbunkus** [comment] 2016-01-04 20:06
Thanks for the feedback. I'm pretty sure it's related to the file (not necessarily the file _type_ but the specific file). The message "mkvmerge executable was not found" is shown if the call to mkvmerge fails in an unexpected way – and that can also be if mkvmerge itself crashes. That's what's happening in the issue I've linked to above. And this particular crash only happens if the file in question contains certain bytes so that mkvmerge thinks it's TrueHD while it actually isn't.

So it's quite possible it's happening with one h.264 file but not the next one even if both are encoded with the same settings.

Anyway. Another user had reported the same problem via email and the test file that he had provided turned out to trigger exactly the aforementioned crash. Therefore I agree that the current issue has already been fixed. I'm therefore closing the issue.

**Closed by mbunkus** 2016-01-04 20:06 UTC

**Comment by r0lZ** [comment] 2016-01-04 20:21
Thanks.

Can you tell me if I should include one of the recent test builds with BD3D2MK3D to be on the safe side, or do you plan to release a new version soon?  I prefer to avoid v8.7.0 if the bug can happen again.

**Comment by r0lZ** [comment] 2016-01-04 20:24
Just a precision: In my case, the bug with the gui was triggered with a VIDEO file ONLY.  Not at all related to TrueHD.  So, the problem might be more global than what you have experienced so far.  (But I must say that I have tried the mux via command line first, and it may have caused the problems later with the GUI and the h264 file.)

**Comment by mbunkus** [comment] 2016-01-04 20:28
I'm thinking about creating a new release soonish (probably on the weekend). You can use today's pre-build, though; the probable release will likely not deviate much from it anyway.

The problem in the TrueHD code was that it accidentally thought the content was TrueHD. Later code in the TrueHD reader then made some more assumptions (which turned out to be false), and then the crash occurred.

**Comment by mbunkus** [comment] 2016-01-04 20:32
Or to put it differently. When you tell mkvmerge to identify or mux a file it will run down a list of supported formats. For each format mkvmerge tries to parse the beginning of the file in question with the code responsible for the format.

Both TrueHD and M2V for which the bug manifested are notoriously difficult to detect this way as they may also occur verbatim inside other formats (e.g. inside MPEG transport streams, MPEG program streams, AVIs…). Therefore those two formats are probed almost last. The TrueHD probing is done much sooner.

Therefore even if you're trying to use a h.264 file it is still run through the TrueHD probing (file type recognition) code. And in that code there was a bug that was triggered by NON-TrueHD content (real TrueHD content wouldn't have caused a crash ironically – it would have just worked).

**Comment by r0lZ** [comment] 2016-01-04 20:38
Understood.  Thanks for the explanation.  I just don't understand why it doesn't crash any more, but that's probably because the conditions are not met.

I'll wait for the new release.  I just re-released the last version of BD3D2MK3D with mkvmerge v8.6.1, and I don't want to release it again immediately.  Next week should be OK.  Thanks in advance for the new version.

**Comment by mbunkus** [comment] 2016-01-04 20:44
Not every file triggers the issue. Far from it, in fact, otherwise I would have caught it myself before the v8.7.0 release already. I do have an ever-growing library of tests and test files I run through for each commit…

I don't make any promises whether or not I'll release within a week, though. It's somewhere between "maybe" and "likely".
