### ISSUE TITLE
mkvextract for vobsub splits off extension at the first dot

### ISSUE THREAD

**Issue by Seegras** [mbunkus/mkvtoolnix#1719] opened 2016-06-07 08:34 UTC
Test case:
`mkvextract tracks movie.mkv 2:subs.language.srt`
(where track 2 is actually a vobsub)

Expected Files:
```
subs.language.idx
subs.language.sub
```
Resulting Files:
```
subs.idx
subs.sub
```

Which of course is futile when used in a script that loops over languages.. 

Expected Behaviour:
mkvxextract should split off the extension at the last dot.

**Comment by mbunkus** [comment] 2016-06-07 08:52
Uhm, which version of mkvextract are you using and on which operating system + which version? I cannot reproduce this with v9.2.0, neither on Windows…

```
C:\temp\mkvtoolnix>mkvextract --ui-language en tracks v.mkv 1:on-windows.lang.idx
Extracting track 1 with the CodecID 'S_VOBSUB' to the file 'on-linux.lang.sub'. Container format: VobSubs
Writing the VobSub index file 'on-windows.lang.idx'.
Progress: 100%

C:\temp\mkvtoolnix>dir on-windows*.*
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: 8C43-B0AA

 Verzeichnis von C:\temp\mkvtoolnix

07.06.2016  10:49            20.253 on-windows.lang.idx
07.06.2016  10:49         1.316.864 on-windows.lang.sub
               2 Datei(en),      1.337.117 Bytes
               0 Verzeichnis(se), 459.946.414.080 Bytes frei
```

…nor on Linux:

```
[0 mosu@sweet-chili ~/prog/video/data] mkvextract tracks v.mkv 1:on-linux.lang.idx
Extracting track 1 with the CodecID 'S_VOBSUB' to the file 'on-linux.lang.sub'. Container format: VobSubs
Writing the VobSub index file 'on-linux.lang.idx'.
Progress: 100%
[0 mosu@sweet-chili ~/prog/video/data] ls -l on-linux*
-rw-rw-r-- 1 mosu vj   19836 Jun  7 10:50 on-linux.lang.idx
-rw-rw-r-- 1 mosu vj 1316864 Jun  7 10:50 on-linux.lang.sub
```

**Comment by Seegras** [comment] 2016-06-08 08:45
Version 9.1.0-1, on Debian. And now of course I destroyed my test-subject...

**Comment by mbunkus** [comment] 2016-06-08 08:52
I cannot reproduce this on Debian Jessie with 9.2.0 either:

```
[0 debian-jessie(64) mosu@debianjessie64-25583 ~/prog/video/data] /usr/bin/mkvextract tracks v.mkv 1:subs.mylang.idx
Extracting track 1 with the CodecID 'S_VOBSUB' to the file 'subs.mylang.sub'. Container format: VobSubs
Writing the VobSub index file 'subs.mylang.idx'.
Progress: 100%
[0 debian-jessie(64) mosu@debianjessie64-25583 ~/prog/video/data] ls -l subs*
-rw-rw-r-- 1 mosu vj   19836 Jun  8 10:49 subs.mylang.idx
-rw-rw-r-- 1 mosu vj 1316864 Jun  8 10:49 subs.mylang.sub
```

If it's an older version of Debian: it is possible that this is related to a bug in Boost in older versions. See #1140. I don't support Debian older than Jessie anymore, though, so I'm going to close this issue as it is working as intended on current distritbutions and versions of Boost.

**Closed by mbunkus** 2016-06-08 08:52 UTC
Labels: app:mkvextract
