### ISSUE TITLE
When going to next chapter by pressing enter...

### ISSUE THREAD

**Issue by ramicio** [mbunkus/mkvtoolnix#1408] opened 2015-08-19 20:16 UTC
Re. bug #1358, when going to next chapter by pressing enter, the same field that was previously being edited should be highlighted. If I am editing names, and I press enter, the name field should be highlighted.

**Comment by mbunkus** [comment] 2015-08-19 21:23
This is at least debatable as different people function differently. Some prefer editing one entry after the other (both time and text), others prefer doing only the texts or only the time for all entries. 

Note that you can simply press enter a second time and you'll be back in the name edit field. Pretty much just as fast as going directly from the name to the name. 

Anyway, this is a duplicate of #1398.

**Closed by mbunkus** 2015-08-19 21:23 UTC
