### ISSUE TITLE
malloc() error for AVI file

### ISSUE THREAD

**Issue by ptr727** [mbunkus/mkvtoolnix#2123] opened 2017-10-10 04:52 UTC
Hi

Trying to remux an AVI file to MKV, and I get what looks like an AVI stream or parsing error.

Using MKV, error:
```
mkvmerge.exe --default-language eng --output foo.mkv --audio-tracks eng --subtitle-tracks eng foo.avi
memory.cpp/safemalloc() called from file src/common/memory.h, line 183: malloc() returned nullptr for a size of 18446744072797760960 bytes.
```

Using ffmpeg, works:
```
ffmpeg.exe -i foo.avi -codec copy foo.mkv
```

But ffmpeg does report some stream warnings:
```
ffmpeg.exe -v warning -i foo.avi -f null -
[mpeg4 @ 0000000002540cc0] ac-tex damaged at 15 18
[mpeg4 @ 0000000002540cc0] Error at MB: 753
[mpeg4 @ 0000000002541660] slice end not reached but screenspace end (49 left 7B7B67, score= -235)
```

The original AVI and the ffmpeg MKV both play fine in MPC-HC.

MediaInfo:
```
General
Complete name                            : foo.avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
File size                                : 352 MiB
Duration                                 : 42 min 10 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 166 kb/s
Writing application                      : Nandub v1.0rc2
Writing library                          : Nandub build 1853/release

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Format profile                           : Simple@L3
Format settings, BVOP                    : No
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : XVID
Codec ID/Hint                            : XviD
Duration                                 : 42 min 10 s
Bit rate                                 : 976 kb/s
Width                                    : 640 pixels
Height                                   : 368 pixels
Display aspect ratio                     : 1.739
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.166
Stream size                              : 294 MiB (84%)
Writing library                          : XviD 0.0.09 (UTC 2003-03-25)

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Mode                                     : Joint stereo
Mode extension                           : MS Stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 42 min 10 s
Bit rate mode                            : Variable
Bit rate                                 : 135 kb/s
Minimum bit rate                         : 96.0 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Stream size                              : 40.7 MiB (12%)
Alignment                                : Aligned on interleaves
Writing library                          : LAME3.92 
Encoding settings                        : -m j -V 1 -q 2 -lowpass 19.5 --vbr-new -b 96
```

Sample AVI here:
https://1drv.ms/u/s!AqeqhT0NczrNh8MpgB0GqjV1E7lt-Q

Running on Windows 10 Pro x64
Using MKVToolNix 16.0.0

**Comment by mbunkus** [comment] 2017-10-10 10:46
Thanks. I'll look into it.

**Comment by mbunkus** [comment] 2017-10-10 12:06
I won't fix this issue.

The problem is that the AVI contains broken data in its index. Both ffmpeg and other tools contain code to deal with such brokenness (of which there was a lot back in the day when AVI was predominant).

mkvmerge uses a library called `avilib` for reading AVI files (not written by myself) whose development has been abandoned a long time ago. This library does not have a workaround for this particular type of brokenness. I have zero interest in implementing such a workaround either as `avilib` is rather old-style C code. Additionally the time required to completely understand this brokenness and how to work around it would be way bigger than the result warrants.

Please just use ffmpeg for muxing this AVI to Matroska, and then continue processing it with mkvmerge.

**Closed by mbunkus** 2017-10-10 12:06 UTC
Labels: app:mkvmerge, os:all, type:bug, v16.0.0
