### ISSUE TITLE
Mkvmerge discards H.264 SPS/PPS from appended file. Breaks playback.

### ISSUE THREAD

**Issue by sneaker2** [mbunkus/mkvtoolnix#1930] opened 2017-04-04 11:37 UTC
I created 2 files using x264. Both have 100% identical SPS/PPS except for seq_parameter_set_id and
pic_parameter_set_id values.
"id1.mkv" uses id 1, "id2.mkv" uses id 2.
I append them using `mkvmerge 10.0.0: mkvmerge -o append.mkv a.mkv +b.mkv`
When playing this append.mkv using ffplay playback stops right in the middle where the ids switch from 1 to 2. Following errors are thrown:
`non-existing PPS 2 referenced
decode_slice_header error
no frame!`

To check I split the append.mkv to split_from_append.mkv-001/2.mkv using `mkvmerge --split timecodes:30s -o split_from_append.mkv.mkv append.mkv`
(Each part was about 21 seconds long so after 30s everything should be from original "id2.mkv")
Again, split_from_append.mkv-002.mkv is not playable. I extract using `mkvextract tracks split_from_append.mkv-002.mkv --raw split_from_append.mkv-002.mkv 0:split_from_append.mkv-002-raw.264`
I check split_from_append.mkv-002-raw.264 using h264_parse and the SPS/PPS ids seem to have been changed from 2 to 1 in the SPS/PPS NALUs but the actual slices still have id 2. This is what seems to break playback.

Samples uploaded to ftp.

**Comment by mbunkus** [comment] 2017-04-04 11:41
The problem is that mkvmerge only uses CodecPrivate from the first file and ignores the one from the second file. You should even receive a warning that the CodecPrivate data doesn't match.

Therefore the resulting file will only contain the SPS and PPS from file 1, not from file 2.

mkvmerge does NOT change the PPS IDs in the NALUs themselves.

I'm not sure whether I want to work on this. The much more common case is that both files use the same set of SPS and PPS IDs, but the content of the referenced SPS and PPS differ. That solution is much harder to fix and something that I consider to be outside of mkvmerge's scope.

**Comment by mbunkus** [comment] 2017-04-04 11:44
To be clear. I consider mkvmerge's support for appending to be limited to files where the CodecPrivate data matches. Everything on top of that is a feature request, not a bug in the software.

**Comment by sneaker2** [comment] 2017-04-04 11:50
> mkvmerge does NOT change the PPS IDs in the NALUs themselves.
But where does the changed data I see in h264_parse come from? I used the --raw switch so I should only be seeing what was in the actual bitstream, not the CodecPrivate.

P.S.: I think I actually mixed up the splitting and extracting files. Ignore those from the upload. But the result is the same, i.e. ids are changed.

**Comment by mbunkus** [comment] 2017-04-04 11:53
Maybe that's just `h264_parse` mis-interpreting data in the absence of those SPS/PPS. The NALU only contains a PPS ID, and the PPS that ID references in turn contains the SPS ID. Therefore: if the PPS referenced by the PPS ID doesn't exist in the file, the tool cannot actually determine the SPS ID. Maybe it just uses the first PPS in that case, resulting in the output of SPS ID = 1.

**Comment by mkver** [comment] 2017-04-04 13:36
I once ran into an issue like this myself and was on the verge to ask whether "compatible" H.264 codec private data could be merged, but I didn't because I found a workaround: If a raw H.264 bitstream contains only compatible SPS and PPS, it will create a Matrosa file with the right codec private data out of it. So you would need to extract both files to elementary streams, add the first one as input file and add the second one as an additional part. (If I remember correctly, attaching the second one produced a different result, but maybe I don't remember correctly.)

**Comment by sneaker2** [comment] 2017-04-04 13:56
Now I cannot even reproduce what I did originally. I believe I must have forgotten the --raw parameter or mixed up the samples or something like that.

If I assume PPS/SPS are not in the id2.mkv bitstream (only in CodecPrivate) then the behavior is as expected. h264_parse cannot read it at all. Sorry for the inconvenience.

**Comment by mbunkus** [comment] 2017-04-04 13:57
:) No problem at all. I'll close this for the time being as I'm not really interested in implementing a more flexible append mechanism that takes care of all kinds of SPS/PPS mismatches and additions.

**Closed by mbunkus** 2017-04-04 13:57 UTC
Labels: app:mkvmerge, os:all, type:enhancement, v10.0.0
