### ISSUE TITLE
video and audio are not synchronous

### ISSUE THREAD

**Issue by letianxia** [mbunkus/mkvtoolnix#2029] opened 2017-07-02 13:59 UTC
When I merged DVD Files from "The Eagles - Hell freeze over 1994 (7.02G)", the result is video and audio are not synchronous

**Comment by mbunkus** [comment] 2017-07-02 14:13
If you want me to look into this, then I'll need the source files. Please upload enough of them to recreate the problem to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server). Thanks.

**Comment by mbunkus** [comment] 2017-07-09 06:40
As I said: please upload a sample file; otherwise I'll have to close the issue again.

**Comment by ajaxxa** [comment] 2017-07-13 10:30
I also have this problem, but I can not upload a sample file because it happens to me with all the movies!
Audio is ahead of the video of about 125ms / 130ms

**Comment by mbunkus** [comment] 2017-07-13 11:25
@ajaxxa The original reporter talks about one specific file (s)he has problems with. You're talking about having such a problem with all files. Those issues are most likely unrelated. Therefore please don't post in this issue, especially as you've opened a separate one for your problem anyway. Thank.

**Comment by letianxia** [comment] 2017-07-15 10:10
Here is a sample original video: "EAGLES Hell Freezes Over (1994) NTSC Remastered" (7.02GB), and it's download webpage is "https://torrentproject.se/?t=hell+freeze+over".

**Comment by letianxia** [comment] 2017-07-15 10:20
If you insist to ask me for uploaded sample files, I will tell you that I have few problems: (1) these days I'm really very busy, (2) size of these files is so big, (3) my upload speed is not ideal. And I will upload it someday, but not so sure.

**Comment by letianxia** [comment] 2017-07-15 10:31
Another way to get my original video directly: 
https://pan.baidu.com/share/link?uk=1258387667&shareid=4007152639&third=0&adapt=pc&fr=ftw#list/path=%2FHell%20Freeze%20Over&parentPath=%2F

**Comment by mbunkus** [comment] 2017-07-15 12:34
Thanks for the info. A couple of questions:

1. How exactly did you mux that DVD rip? Ideally reproduce the settings and show me the command line ("Multiplexer" menu → "Show command line").
2. Which of the two audio tracks were you listening to? The DTS or the PCM one?
3. Which player are you using?

**Comment by mbunkus** [comment] 2017-07-15 12:42
Scratch that. I know what's happening.

That FBI warning at the start should not be accompanied by sound. Unfortunately that information is not stored in the VOB files, but in the other structural files that make up the DVD. mkvmerge simply doesn't support those files and never will.

You can workaround that by delaying the audio tracks with mkvmerge's `--sync` option (corresponding GUI control: `Timecodes and default duration` → `Delay (in ms)` 

I will therefore close this as "won't fix".

**Closed by mbunkus** 2017-07-15 12:42 UTC
Labels: app:mkvmerge
