### ISSUE TITLE
mmg.exe can't be run on WinXP

### ISSUE THREAD

**Issue by GCRaistlin** [mbunkus/mkvtoolnix#1201] opened 2015-05-13 10:49 UTC
mmg.exe can't be run on WinXP. The following error is displayed:
The procedure entry point RegGetValueA could not be located in the dynamic link library ADVAPI32.dll.

**Comment by mbunkus** [comment] 2015-05-13 10:57
Duplicate of #1187 .

**Closed by mbunkus** 2015-05-13 10:57 UTC

**Comment by mbunkus** [comment] 2015-05-13 11:01
Huh… issue 1187 has been delete. Unfortunately.

Windows XP is not supported anymore and hasn't been for close to a year now. That older versions of MKVToolNix still ran was incidental.

See the [list of supported operating systems and versions](/mbunkus/mkvtoolnix/wiki/Officially-supported-operating-systems-and-versions).

**Comment by GCRaistlin** [comment] 2015-05-13 11:21
I believe it's worth to reflect this in the changelog.
