### ISSUE TITLE
Support of AAC with 960 samples/frame

### ISSUE THREAD

**Issue by basicmaster** [mbunkus/mkvtoolnix#2031] opened 2017-07-02 19:18 UTC
AAC allows to store either 1024 or 960 samples per frame. Usually 1024 is used, but DAB+ uses 960. This setting is stored in the `frameLengthFlag` of the `GASpecificConfig`.

When I convert an AAC file (in my case a LATM stream including the `AudioSpecificConfig`) to MKV with `mkvmerge -o test.mkv test.aac`, this setting seems to get lost: VLC plays the file as if 1024 had been used (which is the default for the common AAC decoders when the 960 flag is ignored somehow) - it is played slower and sounds lower pitched. Looking into the code, this flag is currently ignored in `/src/common/aac.cpp`.

I uploaded an affected file as `aac_latm_960.aac` which comes from a DAB+ service.

**Comment by mbunkus** [comment] 2017-07-02 19:23
Thanks. I'll look into it.

**Comment by mbunkus** [comment] 2017-07-03 18:14
Hmm, the problem is that the information from `GASpecificConfig` is currently not stored in Matroska; meaning mkvmerge doesn't have a way of including that information in the Matroska file. A spec modification will be required as well as modifications to all player software reading AAC from Matroska.

At the moment I'm not willing to invest the time here. Therefore I'll close this as won't fix.

**Comment by basicmaster** [comment] 2017-07-03 18:32
Meanwhile I tested to convert a DAB+ recording that is contained in an ISOBMFF container to MKV - this time interestingly, the converted MKV is played correctly. To me it seems that there must be already some means to keep the needed codec init data (at least) from ISOBMFF to MKV.

I uploaded the file (AAC with SBR from a DAB+ service) as `aac_isobmff_960.m4a`.

**Comment by mbunkus** [comment] 2017-07-03 18:36
Oh? Is it stored in CodecPrivate? Hmm… Maybe I mis-read my own code. I'll re-open.

**Comment by mbunkus** [comment] 2017-07-20 20:18
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) that include the functionality are available (build numbers 01532 and higher). They work with both samples you've provided.

**Closed** 2017-07-21 13:10 UTC
Labels: app:mkvmerge, os:all, type:enhancement, v13.0.0

**Comment by basicmaster** [comment] 2017-07-21 17:43
Thanks!
