### ISSUE TITLE
Problem appending wav's in mkvtoolnix v9.2

### ISSUE THREAD

**Issue by Kid-C** [mbunkus/mkvtoolnix#1715] opened 2016-06-05 02:56 UTC
Issue overview:
When appending wav files in mkvtoolnix gui to create an mka audio file, the resultant mka file does not play properly. Sometimes, the initial mux seemingly works, but subsequent muxes result in the problematic behavior described.

Any wav files can be used to reproduce the problem.

As a workaround, I tried appending flac files, but mismatched private codec data was reported by mkvtoolnix, even as the private codec data matched.

I reported this on Doom9 but waited for the new release in v 9.2, where the problem still persists. Using win8.1/mkvtoolnix 9.2.

**Comment by mbunkus** [comment] 2016-06-05 15:33
Thanks for reporting this here, too.

**Comment by mbunkus** [comment] 2016-07-03 10:02
At the moment I cannot reproduce this. Can you please upload sample files to [my FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server)? What I need is the two or more WAV files you're starting out with as well as a precise description of how you're muxing the files and which resulting file(s) shows the problem.

For the latter the command line for each muxing job should suffice. The GUI will show you the command line corresponding to your current mux settings for easy copying & pasting if you go to `Merge` menu → `Show command line`.

Thanks.

**Comment by Kid-C** [comment] 2016-07-03 15:16
Hi - thanks for responding. I packaged 4 16-44 wavs, settings-command lines-logs, 2 mkas, and a text file with the steps I used. It's 300mb. 

Perhaps it's something specific to my environment bc I can reproduce for any wav file I have. 

In any event, I'll upload to your server when I get in.

**Comment by mbunkus** [comment] 2016-07-03 15:17
Thanks!

**Comment by Kid-C** [comment] 2016-07-04 00:09
Problem had to be on my side since no one could confirm.

Problem was with vlc 2.1.5. Upgraded vlc to 2.2.4 and the problem was resolved. I'll post the same on doom9.

**Comment by mbunkus** [comment] 2016-07-04 09:40
Alright, I'll close this for the time being. If it happens again just reply here and I'll re-open it.

**Closed by mbunkus** 2016-07-04 09:40 UTC
Labels: app:mkvmerge, type:bug, v9.2.0
