### ISSUE TITLE
File is logically duplicated by mkvmerge

### ISSUE THREAD

**Issue by DirkSchmitt** [mbunkus/mkvtoolnix#2152] opened 2017-11-19 15:48 UTC
I downloaded via /mediathekview/ the file Tatort-Tatort__Das_letzte_Rennen-1614082588.mp4  
and convert it to mkv with: 
`mkvmerge --verbose --output Tatort-Tatort__Das_letzte_Rennen-1614082588.mkv Tatort-Tatort__Das_letzte_Rennen-1614082588.mp4`

The console output is:
>mkvmerge v18.0.0 ('Apricity') 64-bit
'Tatort-Tatort__Das_letzte_Rennen-1614082588.mp4': Using the demultiplexer for the format 'QuickTime/MP4'.
'Tatort-Tatort__Das_letzte_Rennen-1614082588.mp4' track 0: Using the output module for the format 'AVC/h.264'.
'Tatort-Tatort__Das_letzte_Rennen-1614082588.mp4' track 1: Using the output module for the format 'AAC'.
The file 'Tatort-Tatort__Das_letzte_Rennen-1614082588.mkv' has been opened for writing.
'Tatort-Tatort__Das_letzte_Rennen-1614082588.mp4' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1280/720.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 20 seconds.

During the running the progress goes up to **199%**.

The resulting mkv file consists of a video and an audio track with **duplicated** size.
Viewing the file the following is notable:
- duration is doubled
- the original video is contained twice

**Comment by mbunkus** [comment] 2017-11-19 15:55
That's an interesting effect. Thanks for reporting it.

This definitely doesn't happen with other MP4 files (meaning I haven't found one I can reproduce it with, and it's highly likely that it's due to the header data in that particular file).

Can you upload that MP4 file to my [FTP server](../wiki/FTP-server) so that I can take a look at what's going on, please?

**Comment by DirkSchmitt** [comment] 2017-11-19 16:05
Please fetch from https://user.computer42.org/~dirk/tmp/4bunkus/
The files will expire in 7 days,

**Comment by mbunkus** [comment] 2017-11-19 16:09
Thanks, downloading now.

My guess is that the file contains two copies of the track headers including frame positions & sizes which cause mkvmerge to read all frames twice. If that's the case, I'll have to make mkvmerge recognize such duplication and ignore the second and all following copies.

This isn't entirely trivial as it is legal to have the headers split up all over the file — and if those aren't duplicates, then they all have to be merged. But I'll see to getting it implemented.

**Comment by mbunkus** [comment] 2017-11-19 21:21
Download's complete, and I can reproduce the behavior.

**Comment by mbunkus** [comment] 2017-11-19 22:06
The problem is not that headers are present twice — but that the edit list entries aren't interpreted correctly.

**Comment by mbunkus** [comment] 2017-11-19 22:52
Fixed in 23d04f7905691e0167e359386330850caa4d77c9.

**Closed by mbunkus** 2017-11-19 22:52 UTC
Labels: app:mkvmerge, os:all, res:fixed/implemented, type:bug, v18.0.0

**Comment by remuxer32** [comment] 2017-11-28 23:02
New pre-builds for Windows that contain the fix have been uploaded here:
- https://mkvtoolnix.download/windows/pre/
