### ISSUE TITLE
Merge tool: bug found: program crashes when moving tracks of appended files via drag & drop

### ISSUE THREAD

**Issue by remuxer32** [mbunkus/mkvtoolnix#1441] opened 2015-09-23 03:22 UTC
Seriously: I'm really depressed and pissed off when I still find the same (or similar) bugs in the GUI. This is the next issue where we have the same(?) problem. Sometimes I think to myself that it doesn't matter of how many crashes you fix because the same crash will return in the next release or two, somehow.
Anyway: I'm reporting this bug as I really love and appreciate your program and hard work.

So I have created a short film for you to watch. See: https://www.youtube.com/watch?v=FvxbUw-EHVo 

Summarizing: I have appended two files and then started dragging & dropping tracks very intensively. The final effect is APPCRASH, of course.

Thanks for the quick fix.

**Comment by mbunkus** [comment] 2015-09-23 06:00
That bug isn't back, it more likely has never been gone as I haven't changed anything regarding drag & drop for two releases. If it were easy to fix properly I would have fixed it long ago, you know.

**Comment by remuxer32** [comment] 2015-09-23 11:58
Ah, I see now. Sorry for my hint. I didn't want to hurt you. Just I got upset when I saw that my favourite program crashed.

**Comment by mbunkus** [comment] 2015-09-23 16:56
I've tried to re-create such a crash, without success. I've looked at the source code hard and have NO idea what I might be doing wrong there, what to change or even where to insert debug statements. I will therefore not work on this in the foreseeable future.

**Comment by remuxer32** [comment] 2015-09-23 17:29
That's a bad news of course, but on the other hand you don't have to worry about it because such a bug is very difficult to find for an average (and especially: beginners) user. I mean that only passionate and advanced users like me are able to detect such an extraordinary issue. Usually most people do not drag & drop tracks of appended files at all so there is a high probability that they will not find it = no complaining. Additionally: you need to be very patient and involved in order to discover such rare issues as they are deeply "hidden". And due to the fact that most people are lazy then we can sleep peacefully :)

**Comment by mbunkus** [comment] 2015-09-26 10:31
I've re-worked the way the drag & drop handling of tracks works. I have no idea whether or not that may fix the issue, but I'd appreciate it if you gave it a try (see below for the download location).

Additionally I've inserted several debug messages that I need if it crashes again. In order to be able to see (and save) the debug messages you need [Microsoft's Debug View utility](https://technet.microsoft.com/en-us/library/bb896647.aspx). Just download and start it. Then run [debug build 921](https://www.bunkus.org/videotools/mkvtoolnix/windows/debug/) of the GUI and drag & drop until it crashes.

After the crash go back to debug view. You should see quite a number of messages (the GUI writes a couple of them each time you drop the files). In debug view select »File« → »Save«, save the messages to a file and send me the file with the messages.

I don't need a video of the crash, just those messages.

**Comment by remuxer32** [comment] 2015-09-26 12:37
Thanks for your new (debug) build. I will check that of course and will send the file if there is a crash again.

**Comment by mbunkus** [comment] 2015-09-27 18:11
I've created another debug build for you to test with even more changes and even more debug output :)

**Comment by remuxer32** [comment] 2015-09-27 18:13
Thanks, I will look into it :)

**Comment by remuxer32** [comment] 2015-09-27 18:16
You mean pre-build number 931, right? Because I've noticed that this site is empty: https://www.bunkus.org/videotools/mkvtoolnix/windows/debug/

**Comment by mbunkus** [comment] 2015-09-27 18:39
Uhm… yeah… 931 wasn't supposed to be a pre-build but a debug one. I'll remove it and create a real debug build. Give me two minutes.

**Comment by mbunkus** [comment] 2015-09-27 18:45
Done, build 932.

**Comment by mbunkus** [comment] 2015-09-27 18:45
Aaaaah crap… that's a build without the debug code… re-building…

**Comment by remuxer32** [comment] 2015-09-27 18:46
:D

**Comment by mbunkus** [comment] 2015-09-27 20:05
As a summary for other users:

I've spent more than 12 hours over the last two days trying to get to the bottom of this. I cannot reproduce these crashes at all, neither on Linux nor on Windows, which makes understanding them extremely difficult. No matter how I change the drag & drop handling remuxer32 can still make it crash.

I've therefore decided not to spend any more time on this. I'll leave the bug open, but anyone hit by it please don't expect a timely fix. I don't know when (or in fact if) I will give this another try.

**Comment by mbunkus** [comment] 2015-11-28 08:57
I'm now closing this as "won't fix". I have no way to reproduce it, I haven't the slightest idea what the issue might be let alone how to fix it.

**Closed by mbunkus** 2015-11-28 08:57 UTC
Labels: app:MKVToolNix GUI, type:bug, v8.4.0
