### ISSUE TITLE
Default Track indicator in Multiplexer screen not updated when changed in General Options

### ISSUE THREAD

**Issue by JJMartin1340** [mbunkus/mkvtoolnix#2137] opened 2017-10-17 16:04 UTC
If a video file has subtitles in it, changing the flag in the Properties - General Option window does NOT update the flag in the Default Track In Output in the Tracks, Chapters And Tags part of the Source Files window. I prefer to have subtitles not display automatically, so I allways change it to No, but the displayed flag does not change. It DOES change if the condition is changed for an audio or video track, so it is only subtitles that display incorrectly. 

Whoops - it is suddenly working properly. I was testing a few files to be sure I got the details right and suddenly the flag DOES display properly when changed. So I don't know if your program has an intermittent bug, or my computer does. 

I tried a few more times and sometimes it fails. It may correct itself if I select a video or audio, then come back to a subtitle. Boy, I hate these intermittent problems.

I have version 17.0.0 in Windows 7 64-bit.

**Comment by mbunkus** [comment] 2017-10-17 16:59
I cannot reproduce this. I doubt there's actually a bug, and it's somewhat more likely that you're misunderstanding how mkvmerge sets those flags. Therefore I'm going to close this again. If you manage to reproduce this consistently, then please provide a step-by-step description, and I'll be happy to look into it. But without a way to reproduce a problem, there's nothing I can do about it.

**Closed by mbunkus** 2017-10-17 16:59 UTC

**Comment by mbunkus** [comment] 2017-10-17 17:26
It may be helpful to read [this FAQ entry](../wiki/Default-and-forced-flags-and-default-yes-no-in-the-GUI) about how the "default track" flag is handled by mkvmerge.
