### ISSUE TITLE
Display dimensions not properly set to 720x405 despite --aspect-ratio

### ISSUE THREAD

**Issue by nyuszika7h** [mbunkus/mkvtoolnix#1951] opened 2017-04-21 10:03 UTC
I have a 720x404 .mp4 file which doesn't have the Display Aspect Ratio flag set. When I run mkvmerge with `--aspect-ratio 0:16/9` on it, I expect the display dimensions to be set to 720x405, but they're set to 720x404. You can't encode a H.264 video as 720x405, which would be exactly 16:9, as the width and height must be at least mod 2, so approximate resolutions such as 720x404 are often used. However, the DAR flag has no such limitation. I know the difference is so minimal it's unnoticeable, but I'm a bit pedantic about it, I would like the DAR flag to be set correctly without having to use `--display-dimensions` instead, as some files have a different resolution and I don't want to go through 80 files manually.

**Comment by sneaker2** [comment] 2017-04-21 12:52
> You can't encode a H.264 video as 720x405, which would be exactly 16:9, as the width and height must be at least mod 2

1. You actually can encode non-mod2 H.264
2. Who says display aspect ratio should have the same restrictions as the encoder anyways?

**Comment by nyuszika7h** [comment] 2017-04-21 13:08
1) You can? But anyway, I bet most devices won't be able to decode that. This is irrelevant to the issue anyway.2) I never said it should. The problem here is MKVToolNix sets display dimensions to 720x404 when I use --aspect-ratio, so I have to use `--display-dimensions 0:720x405` instead.

**Comment by sneaker2** [comment] 2017-04-21 14:23
Sorry, I didn't read carefully enough.

**Comment by mbunkus** [comment] 2017-04-21 17:21
At the moment I cannot reproduce this with a sample file I've created:

```
$ mkvmerge -J issue1951.avi|grep pixel_dimensions
        "pixel_dimensions": "720x404"
$ mkvmerge -o v.mkv --aspect-ratio 0:16/9 issue1951.avi
mkvmerge v10.0.0 ('To Drown In You') 64bit
'issue1951.avi': Using the demultiplexer for the format 'AVI'.
'issue1951.avi' track 0: Using the output module for the format 'MPEG-4'.
The file 'v.mkv' has been opened for writing.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 0 seconds.
$ mkvmerge -J v.mkv|grep -E '(pixel|display)_dimensions'
        "display_dimensions": "720x405",
        "pixel_dimensions": "720x404",
```

It's quite possible this only happens in certain circumstances with certain files. Can you please upload a source file for which this happens to [my FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server)? Thanks.

**Comment by mbunkus** [comment] 2017-04-22 07:24
> When I run mkvmerge with --aspect-ratio 0:16/9 on it…

BTW, are you sure that track ID 0 is actually the video track? It's rather common for MP4 files to list their audio track(s) before the video track in the track headers, in mkvmerge assigns track IDs in the order the tracks are found in the file.

**Comment by mbunkus** [comment] 2017-04-30 18:20
Again, can you please provide more information, especially a sample file with which this happens? Otherwise I'll have to close this as I cannot reproduce it, and my tests show that mkvmerge does the right thing with such pixel dimensions.

**Comment by nyuszika7h** [comment] 2017-05-05 09:09
Yes, sorry, I will provide a sample file later today.

**Comment by mbunkus** [comment] 2017-05-20 06:58
Closing due to lack of sample file to test with & the fact that it works just fine with my own sample.

**Closed by mbunkus** 2017-05-20 06:58 UTC
Labels: app:mkvmerge, os:all, type:bug, v10.0.0
