### ISSUE TITLE
Incorrect anamorphic resolution (4:3)

### ISSUE THREAD

**Issue by lstcus** [mbunkus/mkvtoolnix#1726] opened 2016-06-26 21:01 UTC
https://i.imgur.com/Qe81qiI.png

Full frame 720x480 transforms into 720x527 (4:3). So, how is it cropping 2px transforms the image to 720x478 > 720x540 (mkvmerge value) (4:3), whereas it should be 720x524 (ARC).

According to the Aspect Ratio Calculator (ARC):
http://ps-auxw.de/cgi-bin/ar-calc.pl?source_type=ntsc&source_ar=fullscreen&transform_type_1=crop&transform_x_1=720&transform_y_1=478&transform_type_2=none&transform_x_2=&transform_y_2=&transform_type_3=none&transform_x_3=&transform_y_3=&transform_type_4=none&transform_x_4=&transform_y_4=&transform_type_5=none&transform_x_5=&transform_y_5=&transform_type_6=none&transform_x_6=&transform_y_6=&transform_type_7=none&transform_x_7=&transform_y_7=&transform_type_8=none&transform_x_8=&transform_y_8=&keep=true&calculate=Calculate

How do i determine which value is right?

**Comment by mkver** [comment] 2016-06-27 05:49
1. Your input is already a matroska file and as such already should have display width and display height fields at the container level. mkvmerge simply reads these values and reuses them. That's the way it should be.
2. It follows from 1. that this is only an issue of mkvtoolnix if opening.mkv has already been created by mkvmerge (or if we go futher back: if mkvmerge was the program in your workchain that set the matroska fields for display width and height in the first place).
3. Mediainfo mentions two different aspect ratios: One from the container and an "original aspect ratio". Usually this means that the aspect ratio derived from information from the H264 bitstream is different from the information from the container level. Mkvmerge reverts to the bitstream to set the display width and display height values at the container level if the container does not already contain such values. If this is a mkvmerge issue, it would be interesting to know what type of information the bitstream really contains. You can find this out by extracting it with mkvmerge and using [this tool](http://www.w6rz.net/h264_parse.zip) to analyze the bitstream. You can redirect the output (which is normally written to your console) to a file with ">". We would only need the Sequence Parameter Set and the Picture Parameter Set at the beginning of the file.
4. As far as I know, mkvmerge does not take things like "active picture" into account when making it's decision. (There is a similar concept though which is taken into account: The cropping parameters of an H264 bitstream (Ordinary H264 is divided into 16x16 macroblocks. Because 1080 is not divisible by 16 it is "padded" to 1088, i.e. there are 1088 lines in there which are stored and the decoder itself cuts this to 1080 before passing it to the next program in the chain.)) You really can't blame it for this: If I follow your link and the link therein, I arrive at [this table](https://web.archive.org/web/20140218044518/http://lipas.uwasa.fi/~f76998/video/conversion/#conversion_table). It contains an entry for 720x576 videos with pixel aspect ratio 128/117 and an entry for 720x480 with pixel aspect ratio 4320/4739. Your video could come from many sources: It could be converted from a PAL DVD with black bars which have been cut away during reprocessing. Or it could come from an NTSC DVD. The frame rate is not a reliable indicator here, because it could be that someone inverted the PAL speedup (or just had an audio track fitting to the movie played at 23.976fps). And of course it can come from an NTSC DVD. And of course it can come from something completely else than NTSC and PAL. Where shall mkvmerge know this from?
5. Given that H264 is not a valid DVD format and usually not used for SD TV broadcasts, this video has most likely been converted from MPEG2. In this case the correct pixel aspect ratio/display width and height should have been set during the encode. mkvmerge is not an encoder (and never will be). This confirms that this is most likely not an mkvtoolnix issue.

**Comment by lstcus** [comment] 2016-06-27 08:27
The source is Region 2 Japanese DVD 4:3 and in my x264 cli I used the following commands for the correct input: --sar 4320/4739 --input-res 720x478 --fps 24000/1001 

Source:
https://dl.dropboxusercontent.com/u/41099221/tbnm_op.m2v

**Comment by mkver** [comment] 2016-06-27 09:09
--input-res 720x478 is (as far as I know) only used to tell x264 the dimensions of raw input (input without a container which contains the dimension information). It's not used to crop anything (and it does not tell x264 where to crop: at the top or bottom?). If  you're using an x264 version compiled with some filters you can use --vf crop:0,2,0,0 for this.

**Comment by lstcus** [comment] 2016-06-27 09:19
avs script:
MPEG2Source("E:\Encoding\Projects\tbnm_01.d2v")
Crop(0,2,0,0)

x264:
D:\Encoding\Tools\x264.2692kMod.10bit.x86.exe --input-depth 10 --sar 4320/4739 --input-res 720x478 --fps 24000/1001 --preset veryslow --crf 18 --fade-compensate 1.0 --deblock 0:0 --min-keyint 23 --keyint 240 --psy-rd 0.80:0.0 --qcomp 0.60 --aq-mode 3 --aq-strength 0.70 --no-dct-decimate --no-fast-pskip --qpfile "E:\Encoding\Projects\ktbnm_01.txt" --colormatrix bt470bg -o "E:\Encoding\Projects\tbnm_op [DVD].264" "E:\Encoding\Projects\x264_tbnm_op.avs" 2> "E:\Encoding\Projects\x264_memole_op.txt"

**Comment by mbunkus** [comment] 2016-06-27 09:22
Thank you, @mkver, for triaging this. This seems to be a user problem with the usage of `x264` and not a bug in MKVToolNix. mkvmerge only calculates the display dimensions from the information stored in the bitstream: pixel dimensions and SAR. And you're the one specifying the SAR.

The calculation applied is: `display height = pixel height / SAR = 480 * 4739 / 4320 = 526.55555… =~ 527 (rounded)`. I'm going to close this as this is not a `x264` or SAR calculation forum.

**Closed by mbunkus** 2016-06-27 09:22 UTC

**Comment by mkver** [comment] 2016-06-27 09:49
Although it has been closed I still want to add that I cannot reproduce your findings: The command line
x264.exe --vf crop=0:2:0:0 --no-interlaced --sar 4320/4739 -o tbnm.264 tbnm_op.m2v
produces an H264 file with the correct SAR (checked with h264_parse). Merging it with mkvmerge produces a file with display dimensions 720x524 as expected (you can check the display dimensions with mkvinfo; and you can set them with mkvmerge's header editor to anything you want). Mediainfo tells me:
Display aspect ratio           : 1.374
Original display aspect ratio  : 1.373
(The difference here is probably just a rounding issue.)

**Comment by lstcus** [comment] 2016-06-27 10:05
Thanks!

**Comment by lstcus** [comment] 2016-06-27 20:01
You can reproduce the values by setting the aspect ratio of your x264 output to 4:3 in mkvtoolnix.
