### ISSUE TITLE
Moving Files in Job Queue Causes Crashes

### ISSUE THREAD

**Issue by Saurutobi** [mbunkus/mkvtoolnix#1740] opened 2016-07-13 07:35 UTC
Title Says it all. When I open the program again the merging resumes.

Repro(with latest release but it repro-able in past releases too):
Add a few jobs(happens on varying sizes)
Drag&Drop a job up or down the queue
Wait
Program crashes. I haven't witnessed the crash as I'll look away and come back a few seconds later. not sure if it's when it's working on a file or when it's moving to the next job.
Open program again.
Sometimes it'll crash a few times after I reopen, so I clear out the jobs and add them back in the order I wanted them originally and it's no problem.

Only happens after I've Drag&Droped a job up or down the queue, and it's not consistent with crashing. maybe it'll finish no problem, maybe it'll crash.

I hope the repro steps are enough to work with, let me know if you need more in an @mention so I get an email.
Thnx for making this sweet program!
-Saurutobi

edit: I'm seeing labels for other apps, this is for mkvmergeGUI

**Comment by mbunkus** [comment] 2016-07-13 14:27
Thanks for reporting it. I'm pretty sure you mean "MKVToolNix GUI" and not "mkvmergeGUI" as "mkvmergeGUI" has been removed more than a year ago. And it didn't support drag & drop of jobs in the job queue.

**Comment by mbunkus** [comment] 2016-07-13 14:28
So which version of MKVToolNix are you actually talking about? Just to make sure we're on the same page here.

**Comment by Saurutobi** [comment] 2016-07-13 15:05
Sorry, i meant the latest official release of mkvtoolnix.

**Comment by mbunkus** [comment] 2016-07-19 18:16
I'm sorry, but I cannot reproduce such crashes. I've now tried for 45 minutes to make the GUI crash by dragging & dropping wildly while jobs were processed. Not a single crash. Not on Windows, not on Linux.

So please tell me:

1. Are you really using the application called "MKVToolNix GUI"? Look at the window's title bar, it contains the application's name.
2. Which version exactly are you running? The version is also part of the title bar.
3. Are you running the 32bit or the 64bit version?
4. What's your operating system and which version of it are you running?
5. Where exactly did you download the program from?

**Comment by Saurutobi** [comment] 2016-07-19 18:34
1. Yes
2. v9.3.1 ('Mask Machine')
3. 64bit
4. Win7 Ultimate x64, Win7 Enterprise x64, Win10 Enterprise x64, Win10 Home x64. All 4 of these
5. The website the program links to when it notifies of a new update, normally fosshub. https://mkvtoolnix.download/downloads.html  -> http://www.fosshub.com/MKVToolNix.html  I use the x64 Installer

I would suggest trying with big files. This normally happens when I ad a few 10+GB files to the queue and don't want to wait, so I'll move it to the bottom under some 1-3GB files.

Here's the process I use to add to the queue:
Drag&Drop file into Source Files
in Tracks, Chapters and tags I remove subtitles and extra audio streams
Click Start Muxing.(I don't actually use the add to job queue button at all
Repeat

If that's not reproducible, then go ahead and close ticket. I can deal with not moving stuff in the jobqueue.
Thanks for looking into this.

**Comment by mbunkus** [comment] 2016-07-19 18:43
Thanks for the quick feedback. I'll try with a couple of Blu-rays later.

**Comment by mbunkus** [comment] 2016-07-20 17:30
I still cannot reproduce it, not even with a mix of huge files (> 35 GB) and smaller ones (around 1 GB). Like you suggested I'm going to close this for the time being as it's nearly impossible to fix such issues if I cannot reproduce them. I'm sorry :(

**Closed by mbunkus** 2016-07-20 17:30 UTC
Labels: app:MKVToolNix GUI
