### ISSUE TITLE
Remux ts file to mkv, the FPS are not quite coincident rarely.

### ISSUE THREAD

**Issue by qiangbro** [mbunkus/mkvtoolnix#1791] opened 2016-09-27 07:30 UTC
I'm remuxing a ts file into a new mkv file by using a simple mkvmerge.exe command without extra args:

    mkvmerge.exe source.ts -o output.mkv

Mostly, the FPS of the two files are exactly same number. I have tested a lot of ts file, I found that mkvmerge can automatically set the correct fps for video track, mostly it works fine.
But RARELY, the two FPS are not quite coincident.

at this time, the original FPS of the source ts file is `29.970 (30000/1001)`, but the FPS of output.mkv is `29.970 (29970/1000)`. As you can see, it is not quite coincident.

mkvmerge.exe log:

    mkvmerge v9.4.2 ('So High') 64bit
    'H:\fansub-work\[fansub-dev\ts-sample\蹄の記憶\2016-06-22-2248-2254-蹄の記憶(sample).ts': Using the demultiplexer for the format 'MPEG transport stream'.
    'H:\fansub-work\[fansub-dev\ts-sample\蹄の記憶\2016-06-22-2248-2254-蹄の記憶(sample).ts' track 0: Using the output module for the format 'MPEG-1/2'.
    'H:\fansub-work\[fansub-dev\ts-sample\蹄の記憶\2016-06-22-2248-2254-蹄の記憶(sample).ts' track 1: Using the output module for the format 'AAC'.
    The file 'output.mkv' has been opened for writing.
    Warning: Found at least one B frame without second reference in a non closed GOP.
    Progress: 100%
    The cue entries (the index) are being written...
    Muxing took 9 seconds.

the mediainfo from this ts file:

    General 
    ID : 32742 (0x7FE6) 
    Complete name : H:\fansub-work\[fansub-dev\ts-sample\蹄の記憶\2016-06-22-2248-2254-蹄の記憶(sample).ts 
    Format : MPEG-TS 
    File size : 949 MiB 
    Duration : 8 min 
    Start time : UTC 2016-06-22 22:47:35 
    End time : UTC 2016-06-22 22:55:35 
    Overall bit rate mode : Variable 
    Overall bit rate : 16.4 Mb/s 
    
    Video 
    ID : 256 (0x100) 
    Menu ID : 1072 (0x430) 
    Format : MPEG Video 
    Format version : Version 2 
    Format profile : Main@High 
    Format settings, BVOP : Yes 
    Format settings, Matrix : Custom 
    Format settings, GOP : M=3, N=15 
    Format settings, picture structure : Frame 
    Codec ID : 2 
    Duration : 8 min 
    Bit rate mode : Variable 
    Maximum bit rate : 20.0 Mb/s 
    Width : 1 440 pixels 
    Height : 1 080 pixels 
    Display aspect ratio : 16:9 
    Frame rate : 29.970 (30000/1001) FPS 
    Color space : YUV 
    Chroma subsampling : 4:2:0 
    Bit depth : 8 bits 
    Scan type : Interlaced 
    Scan order : Top Field First 
    Compression mode : Lossy 
    Time code of first frame : 06:02:46:25 
    Time code source : Group of pictures header 
    GOP, Open/Closed : Open 
    Color primaries : BT.709 
    Transfer characteristics : BT.709 
    Matrix coefficients : BT.709 
    ...

the mediainfo from output.mkv:

    General 
    Unique ID : 177322093225354440172799360830015430491 (0x8566FE2FA395C3C0ADE55419749E5F5B) 
    Complete name : H:\fansub-work\[fansub-dev\ts-sample\蹄の記憶\output.mkv 
    Format : Matroska 
    Format version : Version 4 / Version 2 
    File size : 759 MiB 
    Duration : 8 min 
    Overall bit rate mode : Variable 
    Overall bit rate : 13.1 Mb/s 
    Encoded date : UTC 2016-09-27 06:38:41 
    Writing application : mkvmerge v9.4.2 ('So High') 64bit 
    Writing library : libebml v1.3.4 + libmatroska v1.4.5 
    
    Video 
    ID : 1 
    Format : MPEG Video 
    Format version : Version 2 
    Format profile : Main@High 
    Format settings, BVOP : Yes 
    Format settings, Matrix : Custom 
    Format settings, GOP : M=3, N=15 
    Format settings, picture structure : Frame 
    Codec ID : V_MPEG2 
    Codec ID/Info : MPEG 1 or 2 Video 
    Duration : 8 min 
    Bit rate mode : Variable 
    Bit rate : 12.9 Mb/s 
    Maximum bit rate : 20.0 Mb/s 
    Width : 1 440 pixels 
    Height : 1 080 pixels 
    Display aspect ratio : 16:9 
    Frame rate mode : Constant 
    Frame rate : 29.970 (29970/1000) FPS 
    Original frame rate : 29.970 (30000/1001) FPS 
    Color space : YUV 
    Chroma subsampling : 4:2:0 
    Bit depth : 8 bits 
    Scan type : Interlaced 
    Scan order : Top Field First 
    Compression mode : Lossy 
    Bits/(Pixel*Frame) : 0.277 
    Time code of first frame : 06:02:46:25 
    Time code source : Group of pictures header 
    GOP, Open/Closed : Open 
    Stream size : 748 MiB (99%) 
    Default : Yes 
    Forced : No 
    Color primaries : BT.709 
    Transfer characteristics : BT.709 
    Matrix coefficients : BT.709 
    ...

Just use the same cmd `mkvmerge.exe source.ts -o output.mkv`, I also have another ts sample, the original FPS of the source ts file is `29.970 (30000/1001)`, but the FPS of output.mkv goes to `59.940 (59940/1000)`,  not coincident.

mkvmerge.exe log:

    mkvmerge v9.4.2 ('So High') 64bit
    'H:\fansub-work\[任务\2016.05 炎神戦隊ゴーオンジャー\炎神战队电影\2016.04.08 炎神戦隊ゴーオンジャーVSゲキレンジャー\src\2016040817001800-SPHD東映チャンネルＨＤ-炎神戦隊ゴーオンジャーVSゲキレンジャー.ts': Using the demultiplexer for the format 'MPEG transport stream'.
    'H:\fansub-work\[任务\2016.05 炎神戦隊ゴーオンジャー\炎神战队电影\2016.04.08 炎神戦隊ゴーオンジャーVSゲキレンジャー\src\2016040817001800-SPHD東映チャンネルＨＤ-炎神戦隊ゴーオンジャーVSゲキレンジャー.ts' track 0: Using the output module for the format 'AVC/h.264 (unframed)'.
    'H:\fansub-work\[任务\2016.05 炎神戦隊ゴーオンジャー\炎神战队电影\2016.04.08 炎神戦隊ゴーオンジャーVSゲキレンジャー\src\2016040817001800-SPHD東映チャンネルＨＤ-炎神戦隊ゴーオンジャーVSゲキレンジャー.ts' track 1: Using the output module for the format 'AAC'.
    The file 'out.mkv' has been opened for writing.
    'H:\fansub-work\[任务\2016.05 炎神戦隊ゴーオンジャー\炎神战队电影\2016.04.08 炎神戦隊ゴーオンジャーVSゲキレンジャー\src\2016040817001800-SPHD東映チャンネルＨＤ-炎神戦隊ゴーオンジャーVSゲキレンジャー.ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1920/1080.
    Progress: 100%
    The cue entries (the index) are being written...
    Muxing took 2 minutes 29 seconds.

mediainfo from source.ts:

    General 
    ID : 16433 (0x4031) 
    Complete name : H:\fansub-work\[任务\2016.05 炎神戦隊ゴーオンジャー\炎神战队电影\2016.04.08 炎神戦隊ゴーオンジャーVSゲキレンジャー\src\2016040817001800-SPHD東映チャンネルＨＤ-炎神戦隊ゴーオンジャーVSゲキレンジャー.ts 
    Format : MPEG-TS 
    File size : 4.97 GiB 
    Duration : 1 h 0 min 
    Start time : UTC 2016-04-08 16:59:55 
    End time : UTC 2016-04-08 18:00:10 
    Overall bit rate mode : Variable 
    Overall bit rate : 11.8 Mb/s 
    Network name : ---
    Original network name : ---
    
    Video 
    ID : 4101 (0x1005) 
    Menu ID : 33397 (0x8275) 
    Format : AVC 
    Format/Info : Advanced Video Codec 
    Format profile : Main@L4 
    Format settings, CABAC : Yes 
    Format settings, ReFrames : 4 frames 
    Codec ID : 27 
    Duration : 1 h 0 min 
    Bit rate mode : Variable 
    Maximum bit rate : 20.0 Mb/s 
    Width : 1 440 pixels 
    Height : 1 080 pixels 
    Display aspect ratio : 16:9 
    Frame rate : 29.970 (30000/1001) FPS 
    Standard : Component 
    Color space : YUV 
    Chroma subsampling : 4:2:0 
    Bit depth : 8 bits 
    Scan type : Interlaced 
    Scan type, store method : Separated fields 
    Scan order : Top Field First 
    Color range : Limited 
    Color primaries : BT.709 
    Transfer characteristics : BT.709 
    Matrix coefficients : BT.709 
    ...
    

mediainfo from output.mkv:

    General 
    Unique ID : 242584068473500618709395727335287274834 (0xB67FFDFD923BD9D5937DD5F451E9BD52) 
    Complete name : H:\fansub-work\[任务\2016.05 炎神戦隊ゴーオンジャー\炎神战队电影\2016.04.08 炎神戦隊ゴーオンジャーVSゲキレンジャー\src\out.mkv 
    Format : Matroska 
    Format version : Version 4 / Version 2 
    File size : 3.69 GiB 
    Duration : 1 h 0 min 
    Overall bit rate mode : Variable 
    Overall bit rate : 8 762 kb/s 
    Encoded date : UTC 2016-09-27 07:06:54 
    Writing application : mkvmerge v9.4.2 ('So High') 64bit 
    Writing library : libebml v1.3.4 + libmatroska v1.4.5 
    
    Video 
    ID : 1 
    Format : AVC 
    Format/Info : Advanced Video Codec 
    Format profile : Main@L4 
    Format settings, CABAC : Yes 
    Format settings, ReFrames : 4 frames 
    Codec ID : V_MPEG4/ISO/AVC 
    Duration : 1 h 0 min 
    Bit rate mode : Variable 
    Bit rate : 8 619 kb/s 
    Maximum bit rate : 20.0 Mb/s 
    Width : 1 440 pixels 
    Height : 1 080 pixels 
    Display aspect ratio : 16:9 
    Frame rate mode : Variable 
    Frame rate : 59.940 (59940/1000) FPS 
    Original frame rate : 29.970 (30000/1001) FPS 
    Standard : Component 
    Color space : YUV 
    Chroma subsampling : 4:2:0 
    Bit depth : 8 bits 
    Scan type : Interlaced 
    Scan type, store method : Separated fields 
    Scan order : Top Field First 
    Bits/(Pixel*Frame) : 0.092 
    Stream size : 3.63 GiB (98%) 
    Default : Yes 
    Forced : No 
    Color range : Limited 
    Color primaries : BT.709 
    Transfer characteristics : BT.709 
    Matrix coefficients : BT.709 
    ...

**Comment by qiangbro** [comment] 2016-09-27 07:34
I hope mkvmerge can always automatically set the correct fps for video track when I remux ts file to mkv by using the simple cmd: `mkvmerge.exe source.ts -o output.mkv`

**Comment by mbunkus** [comment] 2016-09-27 07:58
I'm sorry, but this is almost certainly not a bug but simply how things work. Matroska [doesn't have a header field for the frame rate](https://github.com/mbunkus/mkvtoolnix/wiki/Wrong-frame-rate-displayed). For TS to Matroska conversion it takes the bitstream's frame rate and uses that for the Matroska "DefaultDuration" element. However, for the actual timestamps of each individual frame mkvmerge will re-use the timestamps from the source file. Those may or may not exactly fit into the frame rate given by the underlying bitstream, but that's hardly mkvmerge's fault.

On top of that MediaInfo does some kind of stochastic analysis in order to display some kind of value as the supposed frame rate of the file. But Matroska simply doesn't have such a header field (like I state above). Therefore that value has to be taken with a grain of salt.

I'll close this issue because mkvmerge is working as it technically should work.

**Closed by mbunkus** 2016-09-27 07:58 UTC
