### ISSUE TITLE
ac3 read from some ts have wrong timecodes

### ISSUE THREAD

**Issue by mkver** [mbunkus/mkvtoolnix#1864] opened 2017-01-24 16:58 UTC
Hello,

today I noticed something odd concerning the timecodes of ac3 streams read from some transport streams: The files produced by mkvmerge have a gap at the beginning of the ac3 streams (all muxes were created with the `--disable-lacing`-switch because of #1700; if one doesn't use it, there is a gap between the first two laces). In all my test files, the gap is always 32ms (one ac3 frame) long. Because it makes no sense to have such a gap (after all, for the ac3-frames coding (and therefore probably transmission) order and presentation order agree), I investigated the issue and now I am certain that this is a bug in mkvmerge:
First, I muxed the file with ffmpeg. Command line:
`ffmpeg -i test.ts -map 0:0 -map 0:3 -c copy -sn ffmpeg.mkv`
There is no gap in the output; more importantly, there is an A/V sync-issue: Because of the gap, all ac3-frames (except the first four) are delayed by 32ms in the file produced by mkvmerge compared to the file produced by ffmpeg (and of course, compared to the other tracks).
Then I cut away the first 10MB (M=10^6) from test.ts (resulting in test2.ts) and muxed it. The result was again a gap of one ac3-frame between the fourth and fifth frame. There was no gap between these two frames in the file muxed from the original transport-stream (without its beginning cut off); the adler-checksums were used here to distinguish the various ac3-frames. This confirms that this is a bug in mkvmerge and that ffmpeg does it probably right.
I also remuxed the transport stream with ffmpeg to another transport stream:
`ffmpeg -i I:\test.ts -map 0 -c copy -sn test.ffmpeg.2.ts`
and remuxed this file with mkvmerge. The result does not exhibit the gap and the A/V sync is just as in the files created directly by ffmpeg. So it only happens on some transport streams. My sample is a recorded satellite stream, It happens with other channels than ZDF and with both of my recording devices.
The other audio streams (MP2-audio) don't suffer from such a phenomenon. I don't have any test files for other audio formats.
If you want to, I can upload other sample files as well. (The files I have mentioned have been uploaded to your ftp-server; I have also cut the first 20MB, 30MB and 40MB of test.ts away and always got the same gap after four ac3 frames.)

Greetings
Andi

**Comment by mbunkus** [comment] 2017-01-24 21:47
Thanks for the report & the files. I'll look into it.

**Comment by mbunkus** [comment] 2017-01-26 08:26
It is a bug in mkvmerge. The issue is that too much data is buffered when reusing existing timestamps from the TS file. Therefore the following timestamp will be used for one AC-3 frame too early.

The TS files in question contain five AC-3 frames in each TS PES packet. Therefore the TS provides one timestamp for five AC-3 frames. What happens is:

1. mkvmerge buffers TS timestamp 1 and the corresponding data.
2. mkvmerge extracts the first AC-3 frame from that data and assigns it the TS timestamp 1.
3. mkvmerge extracts AC-3 frames 2, 3 and 4 and assigns it subsequent timestamps based on TS timestamp 1. So far, so good.
4. mkvmerge now has enough data left for one AC-3 frame, but not a single byte more. Therefore mkvmerge will wait and not write that frame to the output file because it is still looking for dependent frames (which are used in E-AC-3).
5. mkvmerge now reads more data from the TS file, along with it TS timestamp 2 and corresponding data.
6. mkvmerge has now enough AC-3 data buffered to determine that no dependent frame is following, and writes the fifth AC-3 frame to the output file — with the now available TS timestamp 2.

Step 6 is where the bug occurs. TS timestamp 2 is assigned to the fifth AC-3 frame originally coming from TS PES packet 1, hence the gap in timestamps.

I'll fix this.

**Comment by mkver** [comment] 2017-01-26 11:54
Good to hear that you found the problem. I also have sample files where the gap happens after the third AC-3 frame. There are probably four AC-3 frames in each TS PES packet in this stream. If you want I can upload you a sample for testing.
If I understand you correctly, this can only happen for AC-3 (and probably E-AC-3)-tracks because e.g. MP2 doesn't use dependent frames. Is that true? Was it [this committ](https://github.com/mbunkus/mkvtoolnix/commit/39cb977f1c6a169406349b45c963388cddb0b646)? And why was there only one gap?
By the way, which program did you use to analyze the transport stream? That might help me to improve my future bug reports.

**Comment by mbunkus** [comment] 2017-01-26 12:01
> If you want I can upload you a sample for testing.

Not sure if that's really necessary, but it sure wouldn't hurt. Thanks.

> If I understand you correctly, this can only happen for AC-3 (and probably E-AC-3)-tracks because e.g. MP2 doesn't use dependent frames. Is that true?

Well… other track types can have the same issue for similar reasons, e.g. h.264/h.265, where I have to buffer enough to be certain that no more data must be put into the current frame. However, those functions should handle timestamp↔stream position assignments properly.

MP2 does indeed not have that problem because it doesn't require such buffering in the first place.

> Was it this committ?

It was indeed most likely caused by that commit.

> And why was there only one gap?

After the first occurrence of this pattern there's always enough data in the buffer to be able to flush the next frame with an already buffered timestamp. TS timestamp 2 belonging to AC-3 frame 10 will be used for AC-3 frame 9 instead, TS timestamp 3 belonging to AC-3 frame 15 will be used for AC-3 frame 14 etc. There are now always five AC-3 frames between the assignments because when AC-3 frame 14's end is determined AC-3 frame 15's data is already present in the buffer.

> By the way, which program did you use to analyze the transport stream? That might help me to improve my future bug reports.

I didn't analyze the TS stream in this case, I only looked at mkvmerge's behavior and inserted a couple of debug statements regarding timestamps in, timestamps out, stream positions in the AC-3 handling.

**Closed** 2017-01-27 15:08 UTC
Labels: app:mkvmerge

**Comment by mkver** [comment] 2017-01-28 13:14
I have just used the newest pre-build and tested some files. It worked. Great job (as usual)! Thanks.
