### ISSUE TITLE
Subtitle default status displayed incorrectly

### ISSUE THREAD

**Issue by dfsooner** [mbunkus/mkvtoolnix#2127] opened 2017-10-11 14:54 UTC
When loading a file into mkvtoolnix, default subtitles as shown in mediainfo are displayed with "Default track in output"  status set as "no".

**Comment by mkver** [comment] 2017-10-11 15:27
mkvmerge (and the MKVToolNix GUI) only sets the default track flag for one track of its kind (video, audio, subtitles); if you have multiple input files, then it is possible that a track which has a default flag doesn't get the default flag by MKVToolNix because this flag has already been set for another track. It can also happen if your input file has more than one default subtitles. See [here](https://github.com/mbunkus/mkvtoolnix/wiki/Default-and-forced-flags-and-default-yes-no-in-the-GUI) for the algorithm.

**Comment by mbunkus** [comment] 2017-10-11 15:59
In addition to what @mkver has already said: that column shows what the flag will be _in the output file_, not what the flag currently is in the input file. It takes all of the current input files, all of the settings and all of mkvmerge's algorithms into account and shows you what you'll end up with. I'm pretty certain that you aren't observing a bug.

I'll close this issue as "invalid" as it's not a bug. If you ever end up with a file after muxing where the aforementioned column showed something different than what came out, then please provide some evidence (screenshots, sample files etc.). Don't use the GUI's "multiplexer" tool for checking, though; use the GUI's header editor instead. And note that the absence of that element in the file indicates that it is logically set to "true/on" (see [this FAQ entry](../../wiki/Elements-not-showing-up-in-output-file) for why).

**Closed by mbunkus** 2017-10-11 15:59 UTC

**Comment by dfsooner** [comment] 2017-10-11 16:34
Thank you for the clarification.

 

However, when there is only one subtitle in the input file or only one marked as the default, why would the default status be summarily changed to “no” for the output?

**Comment by mbunkus** [comment] 2017-10-11 17:04
Maybe you've configured GUI to set the subtitle tracks to not have the "default" flag set?

**Comment by dfsooner** [comment] 2017-10-11 17:59
You are exactly right.  My bad.  I guess I should review my settings periodically.

 

Please accept my apologies for taking up your time.
