### ISSUE TITLE
mkvmerge's output file does not start at timestamp zero

### ISSUE THREAD

**Issue by stenyak** [mbunkus/mkvtoolnix#1170] opened 2015-04-21 14:35 UTC
I'm unsure if this is the expected behaviour or a bug. If it's a bug, let me know where to privately send the source videos for you to replicate.

The command line used is the following:

    mkvmerge --cluster-length 1 --split timecodes:00:00:00.799500000 -o output%01d.mkv source1.mkv + source2.mkv

The source files have the following mkvinfo -s output:

**source1.mkv**

    Track 1: video, codec ID: V_MPEG4/ISO/AVC (h.264 profile: Main @L4.1), mkvmerge/mkvextract track ID: 0, pixel width: 1920, pixel height: 1080                                                                   
    I frame, track 1, timecode 0 (00:00:00.000), size 128092, adler 0x7a590d5b
    I frame, track 1, timecode 200 (00:00:00.200), size 128284, adler 0x546181d6                            
    I frame, track 1, timecode 800 (00:00:00.800), size 128234, adler 0x3b6e8413                            
    P frame, track 1, timecode 841 (00:00:00.840), size 15134, adler 0xedbf5f07
    P frame, track 1, timecode 880 (00:00:00.880), size 15694, adler 0xa60d90b1                             
    P frame, track 1, timecode 960 (00:00:00.960), size 18883, adler 0x520e96ae                             
    P frame, track 1, timecode 1000 (00:00:01.000), size 14697, adler 0xc95db9e5
    [...]

**source2.mkv**

    Track 1: video, codec ID: V_MPEG4/ISO/AVC (h.264 profile: Main @L4.1), mkvmerge/mkvextract track ID: 0, pixel width: 1920, pixel height: 1080                                                                   
    I frame, track 1, timecode 0 (00:00:00.000), size 128569, adler 0x4df72512
    P frame, track 1, timecode 41 (00:00:00.041), size 15402, adler 0x394118c8                              
    P frame, track 1, timecode 121 (00:00:00.121), size 20184, adler 0x41fc2f78                             
    P frame, track 1, timecode 161 (00:00:00.161), size 15733, adler 0xc3aabb0e                             
    P frame, track 1, timecode 201 (00:00:00.201), size 15105, adler 0x20ab62e5                             
    P frame, track 1, timecode 241 (00:00:00.241), size 15002, adler 0xf06b25e8                             
    P frame, track 1, timecode 321 (00:00:00.321), size 17854, adler 0x074b9ab4                             
    P frame, track 1, timecode 361 (00:00:00.361), size 14762, adler 0x632f9d17                             
    P frame, track 1, timecode 401 (00:00:00.401), size 14488, adler 0xfabd65d1   
    [end]

Now, the split point was 0.799500000s into source1. This means the first output file should have 2 frames, and the second output file will have all the rest of frames.
Inspecting with mkvinfo the two output files, effectively we have:

**output1.mkv**

    Track 1: video, codec ID: V_MPEG4/ISO/AVC (h.264 profile: Main @L4.1), mkvmerge/mkvextract track ID: 0, pixel width: 1920, pixel height: 1080, display width: 1920, display height: 1080                        
    I frame, track 1, timecode 0 (00:00:00.000), size 128092, adler 0x7a590d5b
    I frame, track 1, timecode 200 (00:00:00.200), size 128284, adler 0x546181d6
    [end]

**output2.mkv**

    Track 1: video, codec ID: V_MPEG4/ISO/AVC (h.264 profile: Main @L4.1), mkvmerge/mkvextract track ID: 0, pixel width: 1920, pixel height: 1080, display width: 1920, display height: 1080                        
    I frame, track 1, timecode 600 (00:00:00.600), size 128234, adler 0x3b6e8413
    P frame, track 1, timecode 640 (00:00:00.640), size 15134, adler 0xedbf5f07
    P frame, track 1, timecode 680 (00:00:00.680), size 15694, adler 0xa60d90b1
    P frame, track 1, timecode 760 (00:00:00.760), size 18883, adler 0x520e96ae
    P frame, track 1, timecode 800 (00:00:00.800), size 14697, adler 0xc95db9e5
    P frame, track 1, timecode 881 (00:00:00.881), size 17014, adler 0xc077092a
    [...]

Checking the adler checksums, mkvmerge has split the source files exactly where I wanted them to split.
However, looking at the second output file, you can notice that the first frame starts at 600ms (which happens to be 800ms - 200ms, the timecodes of the 2nd and 3rd frame of source1.mkv!).

Instead, I was expecting each of the output files to start at timecode 0ms. Is that a bug, or a feature? If it's a feature, can I disable it, and have all output files start at timecode zero?

Thanks in advance!

**Comment by mbunkus** [comment] 2015-04-21 14:47
Thanks for posting it and the detailed analysis. At first glance I'd say it's a bug. It would be nice to have access to the two source files for easier debugging. Can you please upload them to my [FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server)? Thanks.

**Comment by stenyak** [comment] 2015-04-21 14:57
Hello, I uploaded the file to ftp://ftp.bunkus.org/mkvtoolnix-issue-1170.zip (pwd via email).
Thanks for looking into the issue!

**Comment by mbunkus** [comment] 2015-04-21 17:55
Hmm, I know what the problem is – mkvmerge doesn't know the duration of the h.264 frames and therefore subtracts too little from the timecodes in the second output file.

Now you might say »just subtract the first timecode from the following output file«, but that wouldn't necessarily be correct either. Certain video sequences (think MPEG-2 open GOP) can have timecodes like I 0ms, P 120ms, B 40ms, B 80ms, I 240ms, B 160ms, B 200ms. Splitting before the the second I frame and subtracting 240ms from all the timecodes following frames would obviously be wrong and result in negative timecodes.

So would mkvmerge would do in order to fix this is queue enough frames in the Matroska reader in order to properly calculate the duration for the frames in question. This is a non-trivial re-write, and I will most likely not fix it soonish.

I don't have a workaround to offer either. The only thing that comes to mind is doing a second re-mux, only re-muxing the second file and using the `--sync` option on all the tracks.

**Comment by stenyak** [comment] 2015-04-22 07:08
Thanks for the explanation. I have two questions:

a) I am in control of the muxing of the source mkv files, using gstreamer. Currently I set the buffer "timestamp" (which translates into mkv timecode), but not the "duration" of each frame. If I managed to compute them correctly, would mkvmerge be able to work correctly then?
I jus tested a naive approach of this (assigning current_buffer.duration = current_buffer.timestamp - previous_buffer.timestamp in my gstreamer muxing pipeline), but I am still getting non-zero initial timecodes in the resulting mkvmerged mkv files. I suppose this is because I'm setting the duration of immediately previous frame, instead of duration of the current frame...

b) If those 600ms really do come from (800-200), then I am able to compute the amount before I call mkvmerge. That being the case, and knowing I will never receive B-frames in my use cases, could I pass the suggested --sync flag directly on the first remux and get a zero-timecoded first frame, without going through a costly second remux?

**Comment by mbunkus** [comment] 2015-04-22 07:25
When reading a Matroska file a player should dervice a frame's duration with the following algorithm (aborting after the first step that succeeds):

1. For BlockGroup elements that contain a Duration elemen that duration is used (well, `frame duration = block duration / number of frames in block`).
2. If the track has a DefaultDuration element then that value is used.
3. Otherwise the difference between the next frame's timecode in presentation order (!) and the current frame's timecode should be used.

mkvmerge can do 1. and 2., but currently it doesn't do 3. This works well enough for most cases.

So if you do know the duration and if you do write BlockGroups with a proper Duration element then mkvmerge should do the right thing with that information.

As for your second question: no, that won't work because `--sync` will be applied to all fames, not just the ones written to the second output file. There's no way to apply certain settings to certain output files only (the value `--sync` is actually handled and applied long before the splitting decision is made).

Some more background: if segment linking is used during splitting (the `--link` option) then mkvmerge will not adjust the timecodes. However, segment linking is seldom used, and people usually expect all output files to start at 0. For this mkvmerge keeps track of the maximum `frame's timecode+corresponding duration` written so far. When mkvmerge starts a new output file that previous maximum is then subtracted from all files, hence you needing the duration in your case – or more precisely that's why mkvmerge only subtracts 200ms. As mkvmerge only has a duration of 0ms for that frame the maximum to subtract is still 200ms.

**Comment by stenyak** [comment] 2015-04-22 07:31
Thanks for the insight.
It looks like I may be in luck: in my specific use case, I always discard the first output file (I keep only the second output file), so if --sync shifts the first output file incorrectly it wouldn't be a problem at all for me.

As for correctly setting duration in the first place, I'm unsure what I'm doing wrong but I'm unable to make it "stick" during the muxing of the souce files. Is there any quick way to check which of the three methods is needed to be used for certain MKV file? mkvinfo -v or -s do not seem to show this I think. This last question is just curiosity, since it looks like --sync can solve my problems :-)

**Comment by mbunkus** [comment] 2015-04-22 07:38
Run `mkvinfo -v -v yourfile.mkv`. If a frame is in a BlockGroup element with a Duration child then method 1 is used for that frame. For all other frames look for `DefaultDuration` in the track headers. If there's such an element that its value will be used for those other frames. Otherwise the duration is 0ms.

**Comment by stenyak** [comment] 2015-04-28 13:34
I seem to be having problems using the --sync flag. I try adding --sync -1:-600 but the resulting file is still starting at != zero timecode (I use TID -1 because TID 0 results in error). Any hints?

**Comment by mbunkus** [comment] 2015-04-28 18:52
First of all: what kind of error? Can you paste it, please?

Second: what the command line you've used? Keep in mind that options like `--sync` apply to the following source file only.

**Comment by stenyak** [comment] 2015-04-29 10:13
It looks like I was using --sync incorrectly. The correct way, in my case, is to completely omit the --split option, and rely solely on --sync, which will implicitely discard frames with negative timecodes, thus generating a single MKV file (equivalent to the 2nd output file if I had used --split flag), whose first frame starts at timecode zero (exactly what I want).

As a bonus, using --sync instead of --split, mkvmerge doesn't create the first output file (which I was going to delete anyway), so it reduces the IO load on that disk.



Regarding the TID 0 error, it was my mistake. I read the mkvmerge manual too fast, where it says that AVI video tracks have TID==0. However these are matroska files, and inspecting them with mkvinfo reveals a TID of 1. So I can use either -1, or the actual number 1. Sorry for the confusion.

For the record, the "error" was a -1 exit code (which TFM says is a warning), and indeed this warning message showed on screen:

    Warning: 'source1.mkv': A track with the ID 0 was requested but not found in the file. The corresponding option will be ignored.

So after realizing that mistake, all is fine now.

Thanks a lot for the help and for your work on mkvtoolnix!

**Comment by mbunkus** [comment] 2015-05-30 20:55
As you've got a workaround and as this is very time-consuming and complex to fix I will likely not tackle it any time soon. I will leave this issue open until then, of course, as the underlying issue hasn't been fixed yet.

Just a small correction: an exit code of -1 (meaning a negative exit code) is definitely not a warning; it's usually a segmentation fault. My tools only use the exit codes 0, 1 and 2 (positive 1 and positive 2) with 1 indicating a warning but no errors and 2 indicating an error (and possibly warnings).

**Comment by mbunkus** [comment] 2015-10-10 15:06
I've come to the conclusion that I will most likely never tackle this particular issue. I'll therefore close it as won't fix.

**Closed** 2015-10-10 18:43 UTC
Labels: app:mkvmerge, os:all, res:wontfix, type:bug, v7.8.0
