### ISSUE TITLE
MKVToolNix GUI has crashed when a free space on disk is ending during job processing

### ISSUE THREAD

**Issue by fatalistt** [mbunkus/mkvtoolnix#1300] opened 2015-06-25 20:06 UTC
I created job to merge 2 files in one which was supposed to have about 6 GB, but my drive has only 3 GB of free space. And when these 3 GB is gone, programm just crashed.
I suggest:
1st - compare free space and estimated size of result file (at least as a sum of all tracks plus header etc.)
2nd - correct handle such errors with fie system (i had another error with file system, but i don't know yet, how to reproduce it on another computer)

**Comment by mbunkus** [comment] 2015-06-25 21:15
Thanks for the report. I'll get it fixed.

Note that estimating the resulting file size reliably is not possible as a lot of container formats don't provide any information about how big a track is.

**Comment by mbunkus** [comment] 2015-06-28 15:08
I cannot reproduce this issue with v8.1.0. I've created a small ram disk, copied mkvmerge.exe and mkvtoolnix-gui.exe into that ram disk, started the GUI from the ram disk, added a file whose size exceeded the free space in the ram disk, set the output file name to the ram disk and started the job. The job runs and halts in the middle. mkvmerge emits an error that there's not enough space left to write to.

After that the GUI stays fully responsive. No crash. I can create a new merge job (and even run it if it writes to another drive). Even quitting the GUI works normally.

Can you please try to re-create this on your end with v8.1.0? And which operating system are you using?

**Comment by fatalistt** [comment] 2015-06-28 15:43
I tried to repoduce it with v8.1.0 and, as you said, GUI works normally now.
Windows 8.1 x64

**Comment by mbunkus** [comment] 2015-06-28 15:45
Thanks for checking. I'll close the issue as »works for me« for the time being. If it happens again then just shout.

**Closed by mbunkus** 2015-06-28 15:45 UTC
Labels: app:MKVToolNix GUI, type:bug, v8.0.0
