### ISSUE TITLE
handling of h.264 OpenGOP is wrong

### ISSUE THREAD

**Issue by rootsandculture** [mbunkus/mkvtoolnix#1671] opened 2016-04-24 19:19 UTC
I'm trying to demux an BD, but it never starts. The HDD shows full activity and the memory starts to increase to hangs the OS. I see the process in the task manager and starts eating all the memory. I tried under Ubuntu and under Win7 and the same happens. Any ideas?

![screenshot from 2016-04-24 16 13 48](https://cloud.githubusercontent.com/assets/12083250/14769810/b8443b1c-0a37-11e6-96ee-6124bcdc8f3a.png)

**Comment by mbunkus** [comment] 2016-04-24 19:22
Upgrade to the current release, v9.1.0, and try again.

**Comment by rootsandculture** [comment] 2016-04-24 19:30
The same happens.

**Comment by mbunkus** [comment] 2016-04-24 19:37
Try de-selecting several of the tracks. If that doesn't help then I'll need access to the source files you're trying to mux in order to say anything else about it.

**Comment by rootsandculture** [comment] 2016-04-24 19:58
I selected the movie only and no way. I'm uploading that .m2ts inside "Never starts Issue"

**Comment by rootsandculture** [comment] 2016-04-24 20:50
Is that enough?

**Comment by mbunkus** [comment] 2016-04-24 20:56
There's a folder but no file in it. If you've aborted the transfer then your client has likely deleted the partially transferred file.

**Comment by rootsandculture** [comment] 2016-04-24 21:00
Ufff, i uploaded 300mb. Please give a look in a while. Thanks!

**Comment by mbunkus** [comment] 2016-04-24 21:03
Either set your client not to remove partially transferred files, or upload the whole file, or split the file into smaller parts before uploading.

**Comment by rootsandculture** [comment] 2016-04-24 21:44
Check it ;)

**Comment by mbunkus** [comment] 2016-04-25 10:44
Thanks. I can reproduce it here and will look into it.

**Comment by mbunkus** [comment] 2016-04-26 19:24
I've uploaded [new pre-builds](https://mkvtoolnix.download/windows/pre/). Build numbers 01199 and higher contain the fix.

**Comment by rootsandculture** [comment] 2016-04-26 19:42
Thanks, are there Linux pre-builds too?

**Comment by mbunkus** [comment] 2016-04-26 19:54
No, those would be too many to build. If you're using Debian or Ubuntu you can easily build [packages from my Git sources](https://mkvtoolnix.download/source.html#debian_ubuntu_package).

**Comment by rootsandculture** [comment] 2016-04-28 15:32
![screenshot from 2016-04-28 12 05 32](https://cloud.githubusercontent.com/assets/12083250/14891049/6323a5e4-0d3b-11e6-92da-00226a88294d.png)
It works now :)

Can you please explain me why the GUI changed from version 6.x and doesn't looks integrated as before? I noticed that under GTK and under Windows too. You can see the first screenshot in this thread that is from 6.7 version in the same Linux distro, looks very different.

**Comment by mbunkus** [comment] 2016-04-29 12:12
The GUI has been rewritten with a different toolkit (Qt instead of wxWidgets) for a variety of reasons. See https://github.com/mbunkus/mkvtoolnix/wiki/MKVToolNix-GUI

**Comment by rootsandculture** [comment] 2016-04-29 12:37
Is there a way to build/compile a GTK version of this software? Sorry for
the noob question but I'm not familiarized with programming / linux.

Cheers

**Comment by mbunkus** [comment] 2016-04-29 12:38
No, it isn't.

**Comment by sneaker2** [comment] 2016-04-30 12:34
You cannot just mark I frames as keyframes. "I frame" only means the frame can be decoded independently of other frames. It does not guarantee successive frames aren't depended on frames before the I frame. That's why we only mark IDR frames and frames marked with recovery point SEI as keyframes.

**Comment by mbunkus** [comment] 2016-05-01 16:53
mkvmerge doesn't mark _all_ I slices as Matroska key frames. Only the ones that are actual key frames and the ones that that in MP4 are marked as random access points with the "rap " atom. Matroska simply doesn't differentiate between those two types.

The sample the user had uploaded doesn't include a single key frame (neither via recovery point NALUs nor as I slices in IDR NALUs). It does contain a lot of slices of type 2 and 7 in non-IDR NALUs (those are the ones contained in the MP4 "rap " atom), though. Those are now marked as key frames in Matroska, and seeking to them does work just fine.

This change affects only one of the two packetizers dealing with h.264. The other code path (e.g. when reading h.264 from MP4 files) has been marking MP4 RAP frames as Matroska since the end of 2015. See #1543 for the corresponding bug, one opened by you yourself ;)

**Comment by sneaker2** [comment] 2016-05-01 17:29
> The sample the user had uploaded doesn't include a single key frame (neither via recovery point NALUs nor as I slices in IDR NALUs). It does contain a lot of slices of type 2 and 7 in non-IDR NALUs (those are the ones contained in the MP4 "rap " atom), though. Those are now marked as key frames in Matroska, and seeking to them does work just fine.

Seeking to them works fine _with this specific sample_. Not with all files. You cannot do this. If you want to do this right you have to deep scan the complete file for references crossing the I frames.

**Comment by mbunkus** [comment] 2016-05-01 18:08
I haven't decided to do this on a whim. I've looked at MP4Box's source code for how it decides what to put into the "rap " atom. Looking at [the code](https://github.com/gpac/gpac/blob/master/src/media_tools/media_import.c#L5121) MP4Box doesn't seem to do any kind of reference checking when deciding which frames to put into it. That decision is based on the recovery point SEI info and the slice type.

So what exactly are you saying? That the frames MP4Box put into the "rap " atom cannot always be used for seeking?

**Comment by sneaker2** [comment] 2016-05-01 18:26
No. I am saying you must either be misinterpreting the code or made an error while trying to copy the idea behind it.

**Comment by sneaker2** [comment] 2016-05-01 19:25
Or maybe mp4box has a special mode that makes it mark all slice_type=2 or 7 as rap for your sample but not others? I cannot tell because the code is too complicated for me to understand and I do not have access to the sample you are talking about.
I just uploaded a sample which has an additional frame marked as keyframe by the mkvmerge pre version compared to both mp4box and latest stable mkvmerge. All frame counts are in display order starting from #0. The problematic frame is frame #9 which has slice_type=7. Frame #10 uses frames #9, #8 and #7. Subsequently the frame is neither flagged as IDR nor as a recovery point and should not be marked as keyframe. (Frames #11 and #13 have similar dependencies)

**Comment by mbunkus** [comment] 2016-05-01 19:30
Thanks for the samples. I'll investigate this further.

Let me use this opportunity to say how disgusted I am at AVC's and HEVC's complexity. Is it so bad to make inclusion in contains so hard? No other video codec that I've implemented support for requires as much code and deep parsing as those two do… End of rant.

**Comment by mbunkus** [comment] 2017-07-02 17:30
@sneaker2 At the moment I have my problems finding a sample where MP4Box and mkvmerge mark different frames as I frames. The file you uploaded back then (`issue_1671_non_seekable_slice_type_7.264`) doesn't show a difference:

 * Importing to MP4 with today's MP4Box and then muxing to Matroska results in four frames marked as key frames: at 0.000, at 10.417, at 11.875 and at 15.750.
  * Directly muxing the `.264` into Matroska results in the same four frames marked as key frames and no others.

The same applies to the file the original reporter had uploaded.

The file provided in #2028 exposes a different kind of problem, not one of key frame detetcion.

Do you happen to have another file where mkvmerge and MP4Box differ regarding key frame detection?

**Comment by sneaker2** [comment] 2017-07-02 18:19
I don't.
IIRC the `issue_1671_non_seekable_slice_type_7.264` sample only showed a difference with a never released mkvmerge version. It was supposed to show a problem with the change you reverted:
https://github.com/mbunkus/mkvtoolnix/commit/8b56a68d182f81704c9ee3f75c8ea1f15e2683d8

You would need to look at the sample _rootsandculture_ uploaded (which I don't have access to) to look for differences between mp4box and mkvmerge.

**Comment by mbunkus** [comment] 2017-07-02 18:50
Alright.

Like I said MP4Box and mkvmerge handle the sample uploaded by the original poster identically (which means that only the first frame is detected as a key frame, no other frame). Therefore I don't have a sample to work with at the moment.

I'll close this issue for the time being.

**Closed by mbunkus** 2017-07-02 18:50 UTC
Labels: app:mkvmerge, os:all, type:bug, v9.1.0

**Comment by sneaker2** [comment] 2017-07-02 18:58
Maybe we should track down the change in mp4box and ask the devs about it. It could be non-intentional. Unfortunately I don't have _rootsandculture_'s sample.

**Comment by mbunkus** [comment] 2017-07-02 19:28
I don't think MP4Box has ever treated the original sample differently than mkvmerge. It's basically the same issue as #1876, albeit in an MPEG transport stream from which I extracted the h.264 file with `ffmpeg -i 00047.m2ts -c copy out.264`.
