### ISSUE TITLE
mkvmerge 9.7.1 generates corrupted output

### ISSUE THREAD

**Issue by ericzutter** [mbunkus/mkvtoolnix#1859] opened 2017-01-19 17:37 UTC
I am using "MkvToolNix GUI 9.7.1" 64 bit and "K-Lite_Codec_Pack_1280_Mega.exe" on Windows 7.

There are 2 problems :
1. Generating 2 times same output file, creates 2 outputfiles who are not identical.
2. Input file plays correctly in MediaPlayerClassic but output file contains corrupted part.

I suppose that the 2 problems are related.

See here the codecs in the .MKV input file that has a size of 1 GB :
![image](https://cloud.githubusercontent.com/assets/4773453/22115564/c73f30f8-de6d-11e6-8905-2b613c02cf97.png)

The video contains codecs : HEVC + E-AC3 + ASS

I open the .MKV with MkvToolnix, I don't change anything in the parameters, and click directly on button "Start multiplexing". I do this 2 times so that I have 2 new output files : test2.mkv and test3.mkv. test2.mkv and test3.mkv should be identical but a comparison of the 2 files finds differences (see red color) :

![image](https://cloud.githubusercontent.com/assets/4773453/22115456/522410b8-de6d-11e6-95dc-048580d91bc4.png)

Another test that I did. Modify SubStationAlpha properties : enable default flag, enable force flag, language English. Generate 2 times an output file : test4.mkv and test5.mkv. test4.mkv and test5.mkv should be identical but a comparison of the 2 files finds differences. When I play the video test4.mkv with MediaPlayerClassic or VLC, when he arrives somewhere at the beginning of the video, he finds a corrupted part and the video directly jumps to the end of the video. When I play test5.mkv, I have the same problem but the corrupted part is at another location.

When I play the original video, the video plays normally and don't jump to the end of the video.

**Comment by mkver** [comment] 2017-01-19 19:06
1. That the output files aren't identical is a design choice; it's not a bug. Every matroska file (actually every "segment", but files usually contain only one segment) contains a unique, randomly generated id of 128 bit to support file linking. (128 bit ensures that the possibility that the "unique id" isn't unique at all is so low that it won't happen in real life. (At least, we can neglect it.)) And it contains the time of creation of these files. Your screenshot shows the file header -- exactly where these differences are. Are these the only differences?
2. If you want to create reproducible files, you can use the `--engage no_variable_data`-switch.
3. Here is another way to check if the new files are corrupted: Use `mkvinfo -c -s <your file>` to calculate the adler32-checksum of the individual packets of your file and compare them. (You can also use ffmpeg and its framehash-function for this.)
4. I currently have no clue why the players can't play your new files properly. Does MPC-HC play it right? If not, you should upload it to Moritz' ftp-server.

**Comment by mbunkus** [comment] 2017-01-19 21:44
> 1. Generating 2 times same output file, creates 2 outputfiles who are not identical.

As @mkver has said, this assumption is false. See [this FAQ entry](/mbunkus/mkvtoolnix/wiki/Creating-byte-identical-files) for more details.

> 2. Input file plays correctly in MediaPlayerClassic but output file contains corrupted part.

This shouldn't happen. There have been similar isolated reports in the past, but I've never been able to reproduce such issues myself in spite of spending several days on it. In most of those cases it turned out that the output file was written to USB devices (external hard drive, pen drive…), and the problem vanished miraculously once the user changed to writing to an internal hard drive or a network share. Turning off Windows' caching for the device seemed to fix it for other users.

So if you want me to look into it, I need access to the source files and the exact settings you've used. So please upload the files and the settings (created via the GUI's "Multiplexer" → "Save" option) to [my FTP server](/mbunkus/mkvtoolnix/wiki/FTP-server).

Additionally I need more information: where are you writing your output file to? An internal hard drive, network share, USB connected device, something else?

**Comment by ericzutter** [comment] 2017-01-20 14:47
I play the files with MediaPlayerClassic (= MPC-HC included in "K-Lite_Codec_Pack_1280_Mega.exe" ) and VLC, both have problems viewing outputfiles generated with mkvtoolnix-gui.

The inputfile was located on local drive. The outputfile was written to external USB3 drive. Inside mkvtoolnix-gui I changed SubStationAlpha properties : enable default flag, enable force flag, language English. 

I tested the 2 generated outputfiles with mkvinfo on Windows.

When the inputfile is located in the root folder of the local drive and the 2 outputfiles (output1.mkv and output2.mkv) are located in the root folder of the external USB3 drive then the output of mkvinfo is the same for the 2 files. Mkvinfo output contains no errors (see out1.txt).

When the inputfile is located in the root folder of the local drive and the 2 outputfiles (output5.mkv and output6.mkv) are located in the same folder on external USB3 drive but not in the root folder then mkvinfo shows a different output for each file (see out5.txt and out6.txt).

mkvinfo shows following errors in out5.txt :

output5.mkv: Fout in de Matroska bestand structuur op positie 22486024. Her synchroniseren naar volgende niveau 1 element.
Still resyncing at position 28511613.
Still resyncing at position 34555754.
Her synchroniseren succesvol op positie 38041891.

[out5.txt](https://github.com/mbunkus/mkvtoolnix/files/719593/out5.txt)
[out6.txt](https://github.com/mbunkus/mkvtoolnix/files/719597/out6.txt)
[out1.txt](https://github.com/mbunkus/mkvtoolnix/files/719645/out1.txt)


See here my settings:
[Videos.mtxcfg.txt](https://github.com/mbunkus/mkvtoolnix/files/719623/Videos.mtxcfg.txt)

**Comment by mbunkus** [comment] 2017-01-20 14:57
> When the inputfile is located in the root folder of the local drive and the 2 outputfiles (output1.mkv and output2.mkv) are located in the root folder of the external USB3 drive then the output of mkvinfo is the same for the 2 files. Mkvinfo output contains no errors (see out1.txt).

I'd guess that writing to the root folder on the USB3 drive will show the same type of corruption if you repeat the experiment often enough. Could you please do so?

Then experiment with turning Windows' own caching _off_ for the USB drive.

**Comment by mbunkus** [comment] 2017-01-20 14:59
BTW: which filesystem is used on your drive?

**Comment by ericzutter** [comment] 2017-01-20 15:06
I created on my local drive the same folder structure from USB3-hard-drive and wrote the outputfiles  (output5.mkv and output6.mkv) to same subfolder on local drive. Mkvinfo finds no differences between 2 outputfiles and shows no errors.

So the errors only happen when the outputfiles are located on USB3-hard-drive in a subfolder different of the root folder. But when the outputfiles are located on USB3-hard-drive in the root folder then there are no errors.

**Comment by ericzutter** [comment] 2017-01-20 15:08
Local drive and USB3-drive are both using NTFS filesystem

**Comment by mbunkus** [comment] 2017-01-20 15:12
> But when the outputfiles are located on USB3-hard-drive in the root folder then there are no errors.

What I meant was that I'm pretty sure it will also occur when writing to the USB3 drive's root folder if you write there often enough. Meaning: I'd be really suprised if the location on the USB drive changes the outcome consistently.

**Comment by ericzutter** [comment] 2017-01-20 15:21
I checked my windows write cache settings (I did not change anything):
Local drive has windows write cache enabled.
USB3 drive has windows write cache disabled (= default setting).

So the problem is not related to windows write cache.

**Comment by ericzutter** [comment] 2017-01-20 15:25
I created 2 new outputfiles in root folder of USB3-drive. No errors.

**Comment by mbunkus** [comment] 2017-01-20 15:39
That is… interesting :)

Try a different USB drive (hard drive, pen drive…), different cabling.

**Comment by ericzutter** [comment] 2017-01-20 15:49
Why does mkvtoolnix-gui gives an OK status when writing outputfile and mkvinfo gives an error ?

Is it possible to do the mkvinfo error checks when writing outputfiles with mkvtoolnix-gui, so that mkvtoolnix-gui will give status Failed when writing outputfile ?

**Comment by mbunkus** [comment] 2017-01-20 15:54
The GUI says "ok" because mkvmerge never gets an error from the operating system when writing data. That the data is corrupted on the drive is only recognizable when it is read back in.

Detecting something like this directly in mkvmerge is next to impossible as it would mean having to re-read the whole file after the process has finished. As this can easily take a long time with huge files (or slow devices such as USB2), it is not something I'm willing to add to mkvmerge.

You can configure the GUI to run arbitrary programs once muxing finishes in the GUI's preferences. So if you want such a check, you can write up a batch file/script (in whatever language you prefer) that does just that.

**Comment by mbunkus** [comment] 2017-01-20 16:00
It seems that mkvmerge [isn't the only application](https://social.technet.microsoft.com/Forums/windows/en-US/13a7426e-1a5d-41b0-9e16-19437697f62b/windows-7-64bit-corrupting-altering-large-files-copied-to-external-ntfs-drives?forum=w7itproperf) to show such symptoms.

**Comment by ericzutter** [comment] 2017-01-20 16:48
The USB3-drive that gives problems is a 6 TB USB3 drive.

I tested with another NTFS USB3-drive (4 TB) on the same USB3 port with the same USB3 cable. I wrote the outputfiles to the same subfolder. No errors.

In the past I did a copy of the whole drive 4 TB to drive 6 TB and I did a CRC-check after it. The two drives were identical.

The first time I notice a corrupted file is with mkvtoolnix-gui. The most difficult part is that I receive no error message from Windows when writing the file.

**Comment by mbunkus** [comment] 2017-01-20 16:57
You could do some more tests with TeraCopy and your 6 TB drive. In the thread I've linked to several users report that:

* there's *no* corruption if TeraCopy's option "use system write cache" is *off* but
* there *is* corruption if TeraCopy's option "use system write cache" is *on*.

**Comment by ericzutter** [comment] 2017-01-20 17:13
In your linked thread they also wrote: 

"As others mentioned, the problem is specific to Windows Explorer or cmd copy tools. Teracopy or Total Commander copies do not show this problem."

I used Total Commander to copy the 4 TB drive to 6 TB drive.

Is my 6 TB drive corrupted ? Would buying a new drive make any difference ?

What about mkvtoolnix-gui writing to USB3-drive ? Does mkvtoolnix-gui use a different writing method than Teracopy or Total Commander ?

**Comment by ericzutter** [comment] 2017-01-20 17:46
I disconnected my 4TB-USB3-drive. And reconnected my 6TB-USB3-drive on the same USB3-port. When writing outputfiles to the 6TB-USB3-drive in a subfolder different of root folder, mkvinfo doesn't find any errors. I can not reproduce the error anymore, I suppose it happens randomly.

**Comment by mbunkus** [comment] 2017-01-20 18:19
Please re-do some tests with TeraCopy, not with Total Commander. The reason I'm asking is that TeraCopy offers the user a choice of whether or not to activate the system's own caching mechanism. Please do tests both with TeraCopy's cache checkbox enabled and disabled. What TeraCopy does when the checkbox is disabled is something I can do in mkvmerge, too, hence me asking for tests under both conditions.

With Total Commander you don't have such a choice. My guess is that Total Commander always disables the system's caching mechanism, and consequently the problem doesn't show for people using Total Commander.

**Comment by ericzutter** [comment] 2017-01-20 19:05
I installed TeraCopy : I copied a file from local drive to 6TB-USB3-drive with cache enabled and a second copy with cache disabled. When I compare the 2 copied files they are identical. 

The problem happens randomly. I don't know how I can test it.

If I understand correctly, my USB3-drive is not corrupted, their is only a software bug in Windows ?

**Comment by mbunkus** [comment] 2017-01-20 19:23
That's what everything I've read about this phenomenon leads me to believe, yes: a bug somewhere in Windows. NTFS itself, USB drivers, chipset drivers… And that they only present under certain conditions doesn't make it any easier to deal with.

I'll close this for the time being. If the problem starts backup up for you, just post here and I'll prepare a build with aforementioned caching disabled.

**Closed by mbunkus** 2017-01-20 19:23 UTC
Labels: app:mkvmerge, os:Windows, v9.7.1
