### ISSUE TITLE
mkvinfo.exe error in latest release (7.6.0)

### ISSUE THREAD

**Issue by dorizi** [mbunkus/mkvtoolnix#1120] opened 2015-02-19 10:55 UTC
Hi!
I have downloaded latest release (mkvtoolnix-amd64-7.6.0-setup.exe) and install it.
Extracting tracks (tried on several mkv files) reports

gMKVExtractGUI v1.5.4.0 -- By Gpower2
************************************
An error has occured!
Mkvinfo exited with error code 1!
Errors reported:

Regardin fact that previous version worked I just installed v7.5.0 - copied mkvinfo.exe from this version into temp file. Reinstalled v7.6.0 and replaced mkvinfo.exe with this older version and now I have no error!

Best regards from Slovenia
Dare

**Comment by mbunkus** [comment] 2015-02-19 11:21
The intended behavior is to exit with an exit code of 1 if the program has issued any warning. Unfortunately a bug caused all tools to exit with an exit code of 0 even if warnings were issued up to and including version 7.5.0. This was fixed in 7.6.0.

Therefore this is not a bug in mkvinfo and that GUI will have to be adopted to deal with mkvinfo issuing warnings.

**Closed by mbunkus** 2015-02-19 11:21 UTC
