### ISSUE TITLE
mkvtoolnix-gui: can not add input files

### ISSUE THREAD

**Issue by peter1000** [mbunkus/mkvtoolnix#1246] opened 2015-06-17 14:35 UTC
kind of strange problem. Arch linux qt5.4.2

just compiled `mkvtoolnix` from github

- if I open it by double click and want to add a file it will not do it.
- if I call `./mkvtoolnix-gui` in a terminal 

  it opens with a couple of `libpng warning: iCCP: known incorrect sRGB profile`
  and I can add input files

Have no previous experience with mkvtoolnix.

**Comment by mbunkus** [comment] 2015-06-17 14:37
What exactly do you mean with »it will not do it«? Can you describe in detail where you click on, what happens (preferably with screenshots)?

The warnings are caused by some part of Qt & libpng; there's nothing I can do about them.

**Comment by peter1000** [comment] 2015-06-17 19:21
1. Input > Right Click >  Add files

  ![1](https://cloud.githubusercontent.com/assets/6168860/8216218/866b6f88-150b-11e5-8519-7ee2c24e287e.png)

2. Select a media file

  ![2](https://cloud.githubusercontent.com/assets/6168860/8216226/a1c9e7fa-150b-11e5-953f-880e39488cd4.png)

3. Click open

  ![3](https://cloud.githubusercontent.com/assets/6168860/8216260/da999b70-150b-11e5-9e3f-d775bff33a38.png)

**NOTHING**

---

If I open it from a terminal as user `$ ./mkvtoolnix-gui` and do the exact same steps: I get

  ![4](https://cloud.githubusercontent.com/assets/6168860/8216336/52cb788e-150c-11e5-9f7c-9490feca3373.png)


Anyway if no one else has the problem it might be something with my PC setup - also not a big deal just wanted t let you know.

Don't mind if you close the issue also if none else can reproduce it.

BTW: I tried it with a number of files seems all the same.

**Comment by mbunkus** [comment] 2015-06-18 14:32
It's possible that the $PATH environment variable is different if you run the GUI via double-clicking instead of a shell. The GUI requires mkvmerge to be present somewhere in $PATH.

This shouldn't be a problem if you actually install MKVToolNix, either from a package or with »sudo ./drake install«. Note that other things may not work as expected if you don't install the application.

**Comment by mbunkus** [comment] 2015-06-19 07:27
I can reproduce it if mkvmerge is currently not in a directory in `$PATH`. I'll improve the detection to look for the executable in the same directory that mkvtoolnix-gui is located in (which will work for cases in which MKVToolNix has been installed) and in its parent directory (this will cover the »running from the source tree right after compilation case).

**Comment by mbunkus** [comment] 2015-06-19 11:26
This should be fixed with the commit mentioned above. If it isn't feel free to get back to me.

**Closed by mbunkus** 2015-06-19 11:26 UTC
Labels: app:MKVToolNix GUI, type:bug, v7.9.0

**Comment by peter1000** [comment] 2015-06-20 10:17
thanks I will check this out

**Comment by peter1000** [comment] 2015-06-20 10:52
Seems to work now - Thanks a lot.

**Comment by mbunkus** [comment] 2015-06-20 10:59
Great. Thanks for the confirmation.
