### ISSUE TITLE
MTX crash after moving appended tracks

### ISSUE THREAD

**Issue by hubblec4** [mbunkus/mkvtoolnix#2009] opened 2017-06-11 16:48 UTC
Here is the forum post.
https://forum.doom9.org/showpost.php?p=1809132&postcount=4758

And here the bug video.
https://forum.videohelp.com/attachments/41839-1496967627/MTX-Bug.7z

**Comment by mbunkus** [comment] 2017-06-18 13:20
At the moment I cannot reproduce such a crash, even though I've tried to create similar files regarding the number of tracks and their types. Can you please upload the first 20 MB of both VOB files to my [FTP server](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server), please? Thanks.

**Comment by hubblec4** [comment] 2017-06-18 16:37
Yes I will do this at night.

**Comment by mbunkus** [comment] 2017-06-19 17:15
Thanks, but I cannot reproduce it with those files either, neither on Linux nor on Windows (I'm following the steps you've shown in your video as closely as possible). Means fixing it will be next to impossible for the time being.

**Comment by mbunkus** [comment] 2017-06-20 14:20
We've discussed this via email and agree to close the issue for the time being as I cannot reproduce it at all and hubblec4 can only reproduce it with one particular installation but not with others.

**Comment by hubblec4** [comment] 2017-06-25 11:23
I have used the MTX 13 for a new test.
In a fresh extracted folder, open MTX and there is no Drag-Drop issue.
Now I have copied my "old" mtx-gui.ini in the new fresh folder and the Drag-Drop issue is there again.

Ini is uploaded to your ftp.

**Comment by mbunkus** [comment] 2017-06-25 12:17
Interesting. I can reproduce the issue with your configuration file. Thanks.

**Closed** 2017-06-26 20:10 UTC
Labels: app:MKVToolNix GUI, os:all, type:bug, v13.0.0

**Comment by mbunkus** [comment] 2017-06-26 20:20
Basically I'm convinced that this is actually a bug inside Qt where internal state is somehow corrupted during drag & drop operations if one or more columns are hidden. I've implemented something of a workaround that seems to fix the internal state.

That being said, I haven't debugged Qt itself, and therefore I don't really understand the nature of the corruption, nor why my workaround seems to work. I'm happy enough to leave the workaround in place as it seems to work on both Linux (Qt 5.8) and Windows (Qt 5.7), but I cannot in good conscience claim that this has really been fixed.

Maybe I'll find some more time to create a small test program and to file a bug against Qt.

**Comment by mbunkus** [comment] 2017-06-26 20:25
New [pre-builds for Windows](https://mkvtoolnix.download/windows/pre/) are up.

**Comment by hubblec4** [comment] 2017-06-26 23:00
I can totally understand you, a bug of a compontent and a workaround for that is nothing what let me good sleep.

I will test the new pre-build.

**Comment by hubblec4** [comment] 2017-06-26 23:09
It works. Thanks Mosu.
