### ISSUE TITLE
FPS issue during conversion of mp4 to mkv

### ISSUE THREAD

**Issue by nameaccount** [mbunkus/mkvtoolnix#1649] opened 2016-04-03 15:28 UTC
Hello,

today I noticed two weird issues after the conversion of a mp4 file (the HD.mp4) to mkv using initially mkvtoolnix 8.8.0 and then 9.0.1 (the issue happens with both versions unchanged): 
For some reason, mkvmerge uses the audio track for its "NUMBER_OF_FRAMES"-tag. It writes 64078 in this tag for a file running 22:46.997 minutes which matches the default duration of 21.333ms for an audio track. But normally it writes the number of frames of the video track in this field.
Secondly, mkvmerge writes a default duration of 41.667ms (24 fps) into the mkv header for the video track, although that's wrong. It should be 23.976fps. That matches the number of video frames (32775) and the length of the file. It's also what mediainfo reports.
I uploaded two sample files: For the HD.24fps.mkv file I simply converted the mp4 using 9.0.1 and no additional settings via mkvtoolnix-gui.exe. Then I instructed mkvmerge to cut the first 30s of this mkv (again using the gui and no additional settings). The file is of course a bit longer than 30s.
The only difference of the HD.23.976fps.mkv is that I have manually set the BPS for the video track in the GUI to be 24000/1001 in the first step. This seems to solve the second problem, but not the first.
If I inspect the files with mkvinfo I detect slight discrepancies (not only in the default duration header element): Timestamps of corresponding items are often 1ms apart and in the HD.24fps.mkv mkvtoolnix created a block group at 10841 that it didn't create for HD.23.976fps.mkv. I initially expected that only the default duration header element will be different.
Thanks for your patience and for creating such an awesome tool for free, Moritz!
PS: After I started uploading via filezilla via SFTP filezilla told me that it didn't know your server (hardly surprising) and gave me your credentials to check that I was actually talking to the right counterparty. I tried to doublecheck it, but I couldn't find it [on this page](https://github.com/mbunkus/mkvtoolnix/wiki/FTP-server). You might want to add it there. Anyway, it seems that I have indeed talked to your server.

**Comment by mbunkus** [comment] 2016-04-03 15:57
mkvmerge writes the track statistics tags (which `NUMBER_OF_FRAMES` is a part of) for each track, not just once for the whole file. I don't know why MediaInfo uses the tag from the audio track for reporting it. You'll have to ask the MediaInfo author about it; this is not a bug in mkvmerge.

About the default duration. mkvmerge derives that value from looking at the actual timestamps of all the frames in the MP4 source file. It calculates the duration for each of those frames and uses the one that's most common as the default duration. This is done as the MP4 file signals that it's not using constant frame rate mode. I can look into it, but I don't think I'll invest a lot of time here. Sorry.

**Comment by mbunkus** [comment] 2016-04-03 16:07
To be more precise. The MP4 file has timestamps for each frame. 31954 of those frames have a duration (difference between a frame's timestamp and its successor's timestamp) of 800. The track's timestamp scale is 19200 which means all of those frames have a duration of 800 * 1,000 / 19200 = 41.666… milliseconds. 820 additional frames have a duration of raw 832 yielding 832 * 1,000 / 19200 = 43.333… milliseconds.

This file is simply mastered in a strange way. mkvmerge keeps the timestamps of the frames in the source file (and by extension of their durations). Therefore it has to keep a duration of 41.666ms for the vast majority of all the frames, and hence the default duration = 41.666 is the correct value to use in this case.

Note that by specifying `--default-duration` yourself you're overwriting the duration mkvmerge calculates for each frame. You force the duration to 41.708…ms (= 23.976fps). That's a different case.

Note further that the Matroska file format does NOT have a "frame rate" header field. The default duration is NOT the inverse of the frame rate. See [this FAQ entry](/mbunkus/mkvtoolnix/wiki/Wrong-frame-rate-displayed).

In closing: mkvmerge is working correctly for this particular file.

**Closed by mbunkus** 2016-04-03 16:07 UTC
Labels: app:mkvmerge, os:all, v9.0.1

**Comment by nameaccount** [comment] 2016-04-03 16:51
Thanks for all the effort you put into this! Your answer was almost instantaneously. I now had a second look at mkvinfo and the tags are indeed trackwise. And your answer settles my other question.
PS: And actually your answer raises a new question: The file generated by not overwriting the default duration should be smaller, because more durations don't need to be encoded. But this is not true in my case: The file with the overwritten "default duration" element is smaller (918.577.529 B) than the other one (918.585.389 B) (these are the files from which the samples were cut). Strange, but I can live with it.

**Comment by mbunkus** [comment] 2016-04-03 17:12
Actually, it makes perfect sense :) mkvmerge has to include a "duration" element if and only if a frame's duration is different than the default duration. If you use `--default-duration` then all frames have the same duration as given by the default duration, and extra "duration" elements don't have to be written.

With the standard behavior, however, there are the aforementioned 820 frames whose duration does not match the default duration. For those frames an extra "duration" element has to be written. Additionally if a duration must be written mkvmerge cannot use the space-efficient "simple block" element but has to use the more flexible but also bigger element "block group" for the frame. 

Therefore it's to be expected that the file for which the duration is forced turns out smaller than the one for which it isn't.

**Comment by nameaccount** [comment] 2016-04-03 20:12
Sorry for my misunderstanding. I somehow was under the impression that this field just sets the **default ** duration, not the actual duration and that (regardless of what I prescribe as default duration) the initial duration will always be preserved, i.e. I thought that if I set the default duration to 43.333 ms, that then mkvtoolnix will write the duration for the 31954 frames with duration 41.666 and leave it out for the 820 frames whose duration now matches the default duration. (Or if I set it to 41.708ms that then for every frame a duration element will be written -- 820 with 43.333ms and the 31954 frames with 41.666.)
Thanks for the information.
Now there is only one strange thing left: If I inspect the mkv without forced default duration and look at the block groups, it tells me that they have a duration of 43.000000ms with six decimal places, not 43.333ms. But if I do the math with 43.333ms (or 130/3) then I get the correct result; with 43 ms I am way off. This really seems to be a bug (in mkvinfo, not in mkvmerge). If I stretch all timecodes by a factor of 10 in mkvmerge, mkvinfo tells me that the duration of the block groups are 433.000000ms, not 430ms as it should be if 43ms were correct. In short: mkvinfo claims to be more precise than it is.
I don't know if I should file a separate bug report for this. Feel free to copy the relevant part of this post into a separate ticket.

**Comment by mbunkus** [comment] 2016-04-03 20:14
The precision of timestamps in Matroska depends on the timecode scale value. With the default of 1000000 the precision is 1ms. The precision can be as high as 1ns with a timecode scale value of 1. Therefore mkvinfo outputs more places then it strictly would have to.

**Comment by mbunkus** [comment] 2016-04-03 20:15
And no, please don't file another bug report for this; the behavior is correct as it is even if I don't feel like explaining every little piece of the puzzle at the moment. Thanks.
