### ISSUE TITLE
Display width/height bug

### ISSUE THREAD

**Issue by M7md3li** [mbunkus/mkvtoolnix#2014] opened 2017-06-16 23:17 UTC
When I try to adjust the Display width/height of a video in video properties in MKVToolNix GUI v12.0.0, it does not apply to the video after multiplexing. However, when trying to adjust aspect ratio, it works fine. I was expecting that the video's width and height changes from 1920 x 1080 to 1280 x 720, but the video's width and height stayed the same (1920 x 1080).

**Comment by mkver** [comment] 2017-06-17 00:04
Most players use display wide and height only to determine the aspect _ratio_ of the movie to play, not the actual dimensions. This is their behaviour and nothing MKVToolNix can change, so it is in particular not a bug in MKVToolNix.
Also note that if you really want to change a movie from 1080p to 720p, you have to reencode it. This actually makes sense as it saves space at a quality loss (whereas I don't see much sense in trying to display a 1080p video as 720p).

**Comment by mbunkus** [comment] 2017-06-17 10:31
I'm 99% sure that this isn't a bug in MKVToolNix but players ignoring the actual values and only using their ratio as the display aspect ratio as @mkver has said. I'll therefore close this as "not a bug".

However, you should verify whether or not the header fields have been set correctly: open the file created by the multiplexer in the "header editor" tool and navigate to the video track. Check the "video display width" and "video display height" properties. If the values aren't set to what you've specified for the multiplexing job, then post more details here and I'll re-open the issue.

**Closed by mbunkus** 2017-06-17 10:31 UTC

**Comment by M7md3li** [comment] 2017-06-17 13:39
Thanks guys you were right, the pixels don't change but the width/height do change
It's not a bug, my bad.
